{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(1) 요구사항 정의\n",
    "\n",
    "- 손글씨 숫자 인식\n",
    "- 모델 저장 / 불러오기\n",
    "- 베스트 모델 저장 / 불러오기\n",
    "- 학습 중단\n",
    "- 과대적합 방지 : Dropout\n",
    "- 직접 우리가 손으로 쓴 숫자도 적용해서 인식"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "MINST 손글씨 숫자 데이터셋\n",
    "\n",
    "- 0-9까지의 숫자를 사람이 직접 쓴 데이터 셋\n",
    "- 각 숫자는 28x28 크기로 구성\n",
    "- 훈련데이터 6만개, 테스트데이터 만개"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "\n",
    "physical_devices = tf.config.list_physical_devices('GPU') \n",
    "tf.config.experimental.set_memory_growth(physical_devices[0], True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "데이터 불러오기"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.datasets import mnist\n",
    "\n",
    "(X_train, y_train), (X_test, y_test) = mnist.load_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "((60000, 28, 28), (10000, 28, 28))"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.shape, X_test.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "숫자 이미지 확인"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "7"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAPsAAAD4CAYAAAAq5pAIAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAN7klEQVR4nO3df4xV9ZnH8c+zUkRlguCMLFpWuo1/aCql9YYsshLXCvFXhCaixaRhY1NqIrEoMTWuSU38xxhbQuJana5YWOtUtHXlD7NbQYxpYhovOlXcQaHj2FInMMRorT+CyLN/zHEz4pxzL+ece8+ded6vZHLvPc/58XCZz5w793vufM3dBWDy+7uqGwDQHoQdCIKwA0EQdiAIwg4EMaWdB+vu7vZ58+a185BAKENDQzp06JCNVysUdjO7VNJGSSdI+g93vztr/Xnz5qlerxc5JIAMtVottZb7ZbyZnSDp3yVdJulcSavM7Ny8+wPQWkV+Z18oaZ+7D7r7YUm/krS8nLYAlK1I2M+U9Ocxj/cnyz7HzNaYWd3M6iMjIwUOB6CIImEf702AL1x76+697l5z91pPT0+BwwEookjY90uaO+bxlyW9XawdAK1SJOwvSjrbzL5iZlMlfUfStnLaAlC23ENv7n7EzNZK+h+NDr1tcvfXSusMQKkKjbO7+9OSni6pFwAtxOWyQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAEYQeCIOxAEIQdCIKwA0EQdiAIwg4EQdiBIAg7EARhB4Ig7EAQhB0IgrADQRB2IAjCDgRB2IEgCDsQBGEHgiDsQBCEHQiCsANBEHYgCMIOBEHYgSAKTdlsZkOS3pf0qaQj7l4roykA5SsU9sS/uPuhEvYDoIV4GQ8EUTTsLum3ZrbLzNaMt4KZrTGzupnVR0ZGCh4OQF5Fw77Y3b8p6TJJN5rZkmNXcPded6+5e62np6fg4QDkVSjs7v52cntQ0pOSFpbRFIDy5Q67mZ1iZl2f3Ze0TNLushoDUK4i78bPlvSkmX22n0fd/b9L6QpA6XKH3d0HJX29xF4AtBBDb0AQhB0IgrADQRB2IAjCDgRRxgdhULGHH344tZYMjaY67bTTMusDAwOZ9UWLFmXWL7zwwsw62oczOxAEYQeCIOxAEIQdCIKwA0EQdiAIwg4EMWnG2R999NHM+ssvv5xZ37RpU5nttNW7776be9spU7K/BQ4fPpxZnzZtWmb95JNPTq3Nnz8/c9utW7dm1vnLR8eHMzsQBGEHgiDsQBCEHQiCsANBEHYgCMIOBDGhxtlvueWW1NrGjRsztz169GjZ7UwKjcbRG/n4449z15977rnMba+99trMel9fX2Z99uzZmfVoOLMDQRB2IAjCDgRB2IEgCDsQBGEHgiDsQBATapz98ccfT601Gkdv9Nnpk046KVdPZVi8eHFmfcWKFe1pJIft27dn1rds2ZJaGxoaytx2586dmfVVq1Zl1h977LHUWsTPwjc8s5vZJjM7aGa7xyybZWbPmNne5HZma9sEUFQzL+N/IenSY5bdJmmHu58taUfyGEAHaxh2d39e0jvHLF4uaXNyf7OkFeW2BaBsed+gm+3uw5KU3J6etqKZrTGzupnVR0ZGch4OQFEtfzfe3XvdvebutYhvigCdIm/YD5jZHElKbg+W1xKAVsgb9m2SVif3V0t6qpx2ALSKuXv2CmZ9ki6S1C3pgKQfS/ovSVsl/YOkP0la6e7Hvon3BbVazev1eu5m33jjjdTa7t27U2uStHTp0sx6V1dXrp6QbXBwMLV2xRVXZG67Z8+eQse+9957U2vr168vtO9OVavVVK/Xbbxaw4tq3D3tyoVvFeoKQFtxuSwQBGEHgiDsQBCEHQiCsANBNBx6K1PRoTdMLk888URmfeXKlYX2393dnVqbrJduZw29cWYHgiDsQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAEYQeCIOxAEIQdCIKwA0EQdiAIwg4EQdiBICbUlM2YeO6///7UWqv/tsFHH32UWtu1a1fmtueff37Z7VSOMzsQBGEHgiDsQBCEHQiCsANBEHYgCMIOBME4+yQwPDycWnvkkUcyt92wYUPZ7XxOVm+t9sEHH6TWLr744sxt33vvvbLbqVzDM7uZbTKzg2a2e8yyO83sL2bWn3xd3to2ARTVzMv4X0i6dJzlG9x9QfL1dLltAShbw7C7+/OS3mlDLwBaqMgbdGvN7JXkZf7MtJXMbI2Z1c2sPlnn1wImgrxh/5mkr0paIGlY0k/SVnT3XnevuXutp6cn5+EAFJUr7O5+wN0/dfejkn4uaWG5bQEoW66wm9mcMQ+/LWl32roAOkPDcXYz65N0kaRuM9sv6ceSLjKzBZJc0pCkH7Suxclv+/btmfVGn71+8MEHU2tvvvlmrp4mu+uvv77qFtquYdjdfdU4ix9qQS8AWojLZYEgCDsQBGEHgiDsQBCEHQiCj7iWYO/evZn1G264IbP+7LPPltnOcTnrrLMy6zNnpl4J3ZS77rortTZt2rTMbdeuXZtZf/3113P1JElnnHFG7m0nKs7sQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAE4+xNyvqTy/fdd1/mtoODg5n16dOnZ9ZnzJiRWb/55ptTa43Gky+44ILMeqNx+FZq9O9upKurK7V25ZVXFtr3RMSZHQiCsANBEHYgCMIOBEHYgSAIOxAEYQeCYJy9SS+88EJqrdE4+lVXXZVZX79+fWZ9yZIlmfWJqr+/P7P+1ltvFdr/iSeemFo755xzCu17IuLMDgRB2IEgCDsQBGEHgiDsQBCEHQiCsANBMM7epAceeCC1Nn/+/Mxt77jjjrLbmRT27duXWT9w4ECh/V9yySWFtp9sGp7ZzWyume00swEze83Mfpgsn2Vmz5jZ3uS22GwCAFqqmZfxRyStd/dzJP2TpBvN7FxJt0na4e5nS9qRPAbQoRqG3d2H3f2l5P77kgYknSlpuaTNyWqbJa1oUY8ASnBcb9CZ2TxJ35D0e0mz3X1YGv2BIOn0lG3WmFndzOojIyMF2wWQV9NhN7Ppkn4taZ27/7XZ7dy9191r7l7r6enJ0yOAEjQVdjP7kkaD/kt3/02y+ICZzUnqcyQdbE2LAMrQcOjNzEzSQ5IG3P2nY0rbJK2WdHdy+1RLOuwQs2bNSq0xtJZP1seGm3Hqqadm1m+66aZC+59smhlnXyzpu5JeNbP+ZNntGg35VjP7nqQ/SVrZkg4BlKJh2N39d5IspfytctsB0CpcLgsEQdiBIAg7EARhB4Ig7EAQfMQVLXXeeeel1vbs2VNo38uWLcusL1q0qND+JxvO7EAQhB0IgrADQRB2IAjCDgRB2IEgCDsQBOPsaKmhoaHU2pEjRzK3nTFjRmZ93bp1OTqKizM7EARhB4Ig7EAQhB0IgrADQRB2IAjCDgTBODsK6evry6x/+OGHqbWurq7MbXt7ezPrfF79+HBmB4Ig7EAQhB0IgrADQRB2IAjCDgRB2IEgmpmffa6kLZL+XtJRSb3uvtHM7pT0fUkjyaq3u/vTrWoU1fjkk08y6/fcc09mferUqam1q6++OnPba665JrOO49PMRTVHJK1395fMrEvSLjN7JqltcPd7W9cegLI0Mz/7sKTh5P77ZjYg6cxWNwagXMf1O7uZzZP0DUm/TxatNbNXzGyTmc1M2WaNmdXNrD4yMjLeKgDaoOmwm9l0Sb+WtM7d/yrpZ5K+KmmBRs/8PxlvO3fvdfeau9d6enqKdwwgl6bCbmZf0mjQf+nuv5Ekdz/g7p+6+1FJP5e0sHVtAiiqYdjNzCQ9JGnA3X86ZvmcMat9W9Lu8tsDUJZm3o1fLOm7kl41s/5k2e2SVpnZAkkuaUjSD1rQHyo2+rM+3XXXXZdZX7BgQWpt6dKleVpCTs28G/87SeP9jzOmDkwgXEEHBEHYgSAIOxAEYQeCIOxAEIQdCII/JY1MU6Zkf4vceuutbeoERXFmB4Ig7EAQhB0IgrADQRB2IAjCDgRB2IEgzN3bdzCzEUlvjVnULelQ2xo4Pp3aW6f2JdFbXmX2dpa7j/v339oa9i8c3Kzu7rXKGsjQqb11al8SveXVrt54GQ8EQdiBIKoOe2/Fx8/Sqb11al8SveXVlt4q/Z0dQPtUfWYH0CaEHQiikrCb2aVm9rqZ7TOz26roIY2ZDZnZq2bWb2b1invZZGYHzWz3mGWzzOwZM9ub3I47x15Fvd1pZn9Jnrt+M7u8ot7mmtlOMxsws9fM7IfJ8kqfu4y+2vK8tf13djM7QdIbkpZK2i/pRUmr3P1/29pICjMbklRz98ovwDCzJZL+JmmLu38tWXaPpHfc/e7kB+VMd/9Rh/R2p6S/VT2NdzJb0Zyx04xLWiHpX1Xhc5fR1zVqw/NWxZl9oaR97j7o7ocl/UrS8gr66Hju/rykd45ZvFzS5uT+Zo1+s7RdSm8dwd2H3f2l5P77kj6bZrzS5y6jr7aoIuxnSvrzmMf71Vnzvbuk35rZLjNbU3Uz45jt7sPS6DePpNMr7udYDafxbqdjphnvmOcuz/TnRVUR9vGmkuqk8b/F7v5NSZdJujF5uYrmNDWNd7uMM814R8g7/XlRVYR9v6S5Yx5/WdLbFfQxLnd/O7k9KOlJdd5U1Ac+m0E3uT1YcT//r5Om8R5vmnF1wHNX5fTnVYT9RUlnm9lXzGyqpO9I2lZBH19gZqckb5zIzE6RtEydNxX1Nkmrk/urJT1VYS+f0ynTeKdNM66Kn7vKpz9397Z/Sbpco+/I/1HSv1XRQ0pf/yjpD8nXa1X3JqlPoy/rPtHoK6LvSTpN0g5Je5PbWR3U239KelXSKxoN1pyKevtnjf5q+Iqk/uTr8qqfu4y+2vK8cbksEARX0AFBEHYgCMIOBEHYgSAIOxAEYQeCIOxAEP8Hw0QnkNDj3vwAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# 이미지와 레벨 데이터를 가져옴\n",
    "img = X_train[5000]\n",
    "label = y_train[5000]\n",
    "\n",
    "plt.imshow(img, cmap=plt.cm.binary)\n",
    "label"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "전처리\n",
    "\n",
    "- 이미지는 2차원 데이터 -> 신경망에선 1차원데이터로 입력 -> 변환 필요\n",
    "- 이미지 픽셀값들이 0-255범위 -> 분산이 커서 정확도 떨어질 수 있음 -> 0-1사이로 스케일링"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "((60000, 784), (10000, 784))"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 2차원 이미지를 1차원 데이터 변경 (신경망에는 1차원 데이터로 입력되므로)\n",
    "X_train = X_train.reshape((60000, 28*28))\n",
    "X_test = X_test.reshape((10000, 28*28))\n",
    "\n",
    "X_train.shape, X_test.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 0-255범위의 값을 0-1 범위로 변경 (분산을 감소)\n",
    "# 픽셀값들이 정수로 되어있기 때문에 255로 나누면 0과 1만 나오는 문제\n",
    "#     -> 픽셀값들을 실수로 변환한후에 나누어주어야 0과 1사이값으로 나옴\n",
    "X_train = X_train.astype(\"float32\") / 255\n",
    "X_test = X_test.astype(\"float32\") / 255"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8], dtype=uint8)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "pd.Series(y_train).unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([7, 2, 1, 0, 4, 9, 5, 6, 3, 8], dtype=uint8)"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pd.Series(y_test).unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "((60000, 10), (10000, 10))"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 원핫 인코딩\n",
    "from tensorflow.keras.utils import to_categorical\n",
    "\n",
    "y_train_en = to_categorical(y_train)\n",
    "y_test_en = to_categorical(y_test)\n",
    "\n",
    "y_train_en.shape, y_test_en.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "신경망 설계"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "dense (Dense)                (None, 512)               401920    \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 256)               131328    \n",
      "_________________________________________________________________\n",
      "dense_2 (Dense)              (None, 128)               32896     \n",
      "_________________________________________________________________\n",
      "dense_3 (Dense)              (None, 10)                1290      \n",
      "=================================================================\n",
      "Total params: 567,434\n",
      "Trainable params: 567,434\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "\n",
    "model1 = Sequential()\n",
    "\n",
    "# 입력층\n",
    "model1.add(Dense(units=512, input_dim=784, activation=\"relu\"))\n",
    "\n",
    "# 은닉층\n",
    "# units의 수를 늘려가는 방법 : 인코딩 (특성을 추출, 특성을 늘려줌)\n",
    "# units의 수를 줄여가는 방법 : 디코딩 (특성을 정리, 특성을 선택)\n",
    "model1.add(Dense(units=256, activation=\"relu\"))\n",
    "model1.add(Dense(units=128, activation=\"relu\"))\n",
    "\n",
    "# 출력층\n",
    "model1.add(Dense(units=10, activation=\"softmax\"))\n",
    "\n",
    "model1.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "model1.compile(loss=\"categorical_crossentropy\",\n",
    "               optimizer=\"adam\",\n",
    "               metrics=[\"accuracy\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 60000 samples, validate on 10000 samples\n",
      "Epoch 1/10\n",
      "60000/60000 [==============================] - 2s 39us/sample - loss: 0.2336 - accuracy: 0.9292 - val_loss: 0.1048 - val_accuracy: 0.9683\n",
      "Epoch 2/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0849 - accuracy: 0.9739 - val_loss: 0.0863 - val_accuracy: 0.9733\n",
      "Epoch 3/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0573 - accuracy: 0.9822 - val_loss: 0.0819 - val_accuracy: 0.9740\n",
      "Epoch 4/10\n",
      "60000/60000 [==============================] - 1s 18us/sample - loss: 0.0387 - accuracy: 0.9880 - val_loss: 0.0825 - val_accuracy: 0.9757\n",
      "Epoch 5/10\n",
      "60000/60000 [==============================] - 1s 17us/sample - loss: 0.0324 - accuracy: 0.9894 - val_loss: 0.0676 - val_accuracy: 0.9805\n",
      "Epoch 6/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0234 - accuracy: 0.9924 - val_loss: 0.0916 - val_accuracy: 0.9757\n",
      "Epoch 7/10\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0220 - accuracy: 0.9926 - val_loss: 0.0801 - val_accuracy: 0.9777\n",
      "Epoch 8/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0209 - accuracy: 0.9932 - val_loss: 0.0788 - val_accuracy: 0.9801\n",
      "Epoch 9/10\n",
      "60000/60000 [==============================] - 1s 17us/sample - loss: 0.0162 - accuracy: 0.9944 - val_loss: 0.0783 - val_accuracy: 0.9817\n",
      "Epoch 10/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0179 - accuracy: 0.9943 - val_loss: 0.0869 - val_accuracy: 0.9800\n"
     ]
    }
   ],
   "source": [
    "h1 = model1.fit(X_train, y_train_en, epochs=10, batch_size=128,\n",
    "                validation_data=(X_test, y_test_en))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.legend.Legend at 0x27020404e80>"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXoAAAD4CAYAAADiry33AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAApeklEQVR4nO3deXxU5b3H8c/PsAbZQUSiBAVZRMCWRUVFxQWslWKtVWu9UgVplWJb697eeq2tvbVe4JZCUang7lWxvixVKhpsrQuggKyyWgIIAYqsEZL87h/PxEzCQCZkksnMfN+v13nNcs6ceWaUb878znOex9wdERFJX0cluwEiIlKzFPQiImlOQS8ikuYU9CIiaU5BLyKS5uoluwGxtGnTxnNzc5PdDBGRlDF//vyt7t421ro6GfS5ubnMmzcv2c0QEUkZZvbpodapdCMikuYU9CIiaU5BLyKS5upkjT6WAwcOkJ+fT2FhYbKbkpIaNWpETk4O9evXT3ZTRKSWpUzQ5+fn07RpU3JzczGzZDcnpbg727ZtIz8/n06dOiW7OSJSy1KmdFNYWEjr1q0V8kfAzGjdurV+DYlkqJQJekAhXw367kQyV8qUbkREEqK4GDZvhvx82LAh3G7dCmZw1FFlt/Esid62YUM466yEf2QFvYikj8JC2LixfIiX3pbe37QphH1d1K4dfPZZwneroI/Tjh07ePrpp/nBD35QpdddcsklPP3007Ro0aJmGiaSCdxh585Dh3fp7datB7/26KMhJycsgweX3e/Qoey2TZtwxO0OJSVlt/Esidy2Xs1EsoI+Tjt27OAPf/jDQUFfXFxMVlbWIV83c+bMmm6aSGorKYGCgthH4dG3u3cf/Nq2bUNQH388nHFG+fAuvW3WLP62lJZX0kxqBv2tt8KCBYndZ58+MG7cIVffeeedrF69mj59+lC/fn2OPvpo2rdvz4IFC1i6dCnf+MY3WL9+PYWFhYwdO5ZRo0YBZeP27N69m6FDh3LWWWfxz3/+kw4dOvDnP/+Zxo0bx3y/Rx55hClTprB//346d+7ME088QXZ2Nps3b2b06NGsWbMGgEmTJnHmmWcyffp0HnroIcyMXr168cQTTyT2+xE5lAMH4PPPwxF39G2s5yre7tgRSikHDpTfZ1YWHHdcCOpTT4WhQw8O8eOOCzVtqVRqBn0SPPjggyxevJgFCxaQl5fH1772NRYvXvxlv/SpU6fSqlUr9u3bR79+/fjmN79J69aty+1j5cqVPPPMMzzyyCNceeWVvPjii1x77bUx3+/yyy9n5MiRANx777089thjjBkzhh/+8IcMGjSIGTNmUFxczO7du1myZAkPPPAA77zzDm3atGH79u01+2VIeigpCUfJRxrSpbfxdNutXx+aNw9Ls2bhtlOncFsa6NEhfswxIewlIVIz6A9z5F1b+vfvX+7iowkTJjBjxgwA1q9fz8qVKw8K+k6dOtGnTx8AvvrVr7Ju3bpD7n/x4sXce++97Nixg927d3PxxRcD8OabbzJ9+nQAsrKyaN68OdOnT+eKK66gTZs2ALRq1SpRH1MSacMGePPN0OOjqKhsKS4u/7iy5xPxmgMHYO/eUDM+HLMQzKXh3KxZKJecdNLBwX2420aNauc7lphSM+jrgCZNmnx5Py8vjzfeeIN3332X7Oxszj333JgXJzWM+pmZlZXFvn37Drn/66+/npdffpnevXvz+OOPk5eXd8ht3V395OuiXbtgzhz429/gjTdg6dLY22VlhaVevYOXeJ/Pzq7aPrKywknK6ECOFdJNmqRlzTrTKOjj1LRpU3bt2hVz3eeff07Lli3Jzs5m+fLlvPfee9V+v127dtG+fXsOHDjAU089RYcOHQAYPHgwkyZN4tZbb6W4uJg9e/YwePBghg8fzo9+9CNat27N9u3bdVSfDEVFMG9eCPa//Q3efTc816gRnHMOjBgBF1wAnTuXD1z9kZYapqCPU+vWrRk4cCA9e/akcePGtGvX7st1Q4YMYfLkyfTq1YuuXbty+umnV/v97r//fgYMGEDHjh059dRTv/wjM378eEaNGsVjjz1GVlYWkyZN4owzzuCee+5h0KBBZGVlcdppp/H4449Xuw1SCXdYtaos2N96K9SszeC00+AnP4ELL4SBA1W6kKQyr6xGlwR9+/b1ijNMLVu2jO7duyepRelB32ECbNsGs2eXhfunkUl9OnYMoX7hhXD++aFftkgtMrP57t431rq4jujNbAgwHsgCHnX3ByusbwlMBU4CCoHvufviyLqxwEjAgEfcfdwRfg6R2ldYCO+8U1Zn//DDcCTfvHkI9NtvD+HeubNKMFJnVRr0ZpYFTAQuBPKBuWb2irtHn1m6G1jg7sPNrFtk+8Fm1pMQ8v2B/cBrZvYXd1+Z6A+Sqm6++Wbeeeedcs+NHTuWESNGJKlFGa6kBD7+uOyI/e9/h337Qj39jDPgvvtCsPftW2NXMYokWjz/p/YHVrn7GgAzexYYBkQHfQ/g1wDuvtzMcs2sHdAdeM/d90ZeOwcYDvx34j5Caps4cWKymyD5+WXBPns2bNkSnu/RA0aNCsF+zjnQtGly2ylyhOIJ+g7A+qjH+cCACtssBC4H/mFm/YGOQA6wGHjAzFoD+4BLgHmIJNOuXZCXVxbuy5eH59u1K6uzX3BBuHhHJA3EE/SxCo8Vz+A+CIw3swXAx8BHQJG7LzOz3wB/A3YT/iAUxXwTs1HAKIATTjghrsaLVKqwENatg7Vr4YMPQrC//37o9ti4MQwaBCNHhnDv2VN1dklL8QR9PnB81OMcYGP0Bu6+ExgBYOHKnbWRBXd/DHgssu5Xkf0dxN2nAFMg9LqpyoeQDFZUBOvXhyCvuKxbF8ZRKWUWaus//WkI9jPP1FgpkhHiCfq5QBcz6wRsAK4CronewMxaAHvdfT9wI/B2JPwxs2PcfYuZnUAo75yRwPbXmiMdphhg3LhxjBo1iuzs7BpoWZorKQnjc1cM8NL769eXH1s8KyuMZNipUxgIKzc33O/UCbp3B11IJhmo0qB39yIzuwV4ndC9cqq7LzGz0ZH1kwknXaebWTHhJO0NUbt4MVKjPwDc7O7/TvSHqA2HGqY4HuPGjePaa69V0MfiDtu3Hxzg0aH+xRflX3PssSG4zzyzLMRLl5ycMICWiHwprv5h7j4TmFnhuclR998FuhzitWdXp4F1RfQwxRdeeCHHHHMMzz//PF988QXDhw/nvvvuY8+ePVx55ZXk5+dTXFzMz372MzZv3szGjRs577zzaNOmDW+99VbM/X//+99n7ty57Nu3jyuuuIL77rsPgLlz5zJ27Fj27NlDw4YNmT17NtnZ2dxxxx28/vrrmBkjR45kzJgxtfl1VM3u3bFDvHSpOLREy5YhtHv2hK9/vXyQd+wYausiEreU7AichOHoyw1TPGvWLF544QU++OAD3J3LLruMt99+m4KCAo477jj+8pe/AGEMnObNm/Pwww/z1ltvfTm6ZCwPPPAArVq1ori4mMGDB7No0SK6devGt7/9bZ577jn69evHzp07ady4MVOmTGHt2rV89NFH1KtXr+4OS/zhh3DvvfDXv5Z/Pjs7hHZubui2WPGovHnzpDRXJF2lZNAn26xZs5g1axannXYaALt372blypWcffbZ3Hbbbdxxxx1ceumlnH12/D9mnn/+eaZMmUJRURGbNm1i6dKlmBnt27enX79+ADSLzJTzxhtvMHr0aOpFLtipcwOYLVsGP/85vPBCODq/++4weURpkLdtq94tIrUoJYM+2cPRuzt33XUXN91000Hr5s+fz8yZM7nrrru46KKL+PnPf17p/tauXctDDz3E3LlzadmyJddffz2FhYWHHH64zg5LvG5duHJ0+vRQXvnZz8LAXjpCF0kqDTQdp+hhii+++GKmTp3K7sgclhs2bGDLli1s3LiR7Oxsrr32Wm677TY+/PDDg14by86dO2nSpAnNmzdn8+bN/DVS6ujWrRsbN25k7ty5QBi6uKioiIsuuojJkydTVBQuSUh66eazz2DMGDj5ZHjmGRg7Ftasgf/6L4W8SB2Qkkf0yRA9TPHQoUO55pprOOOM0FP06KOP5sknn2TVqlX89Kc/5aijjqJ+/fpMmjQJgFGjRjF06FDat28f82Rs7969Oe200zjllFM48cQTGThwIAANGjTgueeeY8yYMezbt4/GjRvzxhtvcOONN/LJJ5/Qq1cv6tevz8iRI7nllltq78sotX07/Pa3MH487N8PN9wQjuJzcmq/LSJySBqmOIMk7DvcvTvUz37729Bj5uqrQ8mmc+fq71tEjki1hykWAcJwAn/8IzzwABQUwGWXwf33Q69eyW6ZiByGgr6WDRgwgC8qXAD0xBNPcOqppyapRXEoKoLHHw9H7fn5YRz2Bx6ABMykJSI1T0Ffy95///1kNyF+JSXw/POhq+TKlTBgQAj8wYOT3TIRqYKU6nVTF88npIoqfXfu8OqrYd7Tq68OA3/9+c9hsmuFvEjKSZmgb9SoEdu2bVPYHwF3Z9u2bTSKZ4LqvLwwmfXXvw579sBTT8HChaEeXxf77otIpVKmdJOTk0N+fj4FBQXJbkpKatSoETmH6/b4wQdwzz1hXtQOHcJJ1xEjNECYSBpImaCvX78+nTp1SnYz0s/ixaHv+8svQ5s28PDD8P3vQzxH/yKSElIm6CXBVq+GX/wilGaaNg1Xsd56q+ZFFUlDCvpMs2ED/PKX8OijoSzz05/C7bdD69bJbpmI1BAFfabYuhV+8xv4/e/DjEw33RRq8u3bJ7tlIlLDFPTpbufOUHd/+OHQi+a734X//M8wXLCIZAQFfbravx8mTIAHH4Rt2+Cb3wx1+B49kt0yEallCvp0tHo1XHUVzJsHF18cavJ9Y451JCIZQEGfbp57DkaOhKwseOklGD482S0SqROKi2H9+jCaR+myalW43boVTjwRunYtv3Tpkh5TFCvo08XevaF75COPwJlnwtNPh4m0RTJIcXEYdy9WmK9ZEyqapbKzw8jap5wSLiFZswbmzIEnnyzbxgxOOOHgPwBdu4ZpF1LlYnEFfTpYuhSuvDLc3nVXGGVSV7RKmiopKR/mpUFeGubRg8M2bhzCvHv3MIpHly5h6dwZjjsudlDv2RP2tXw5rFhRtvzzn2EqhlLZ2WFStW7dyv8BOPlkOPromv8eqiKuoDezIcB4IAt41N0frLC+JTAVOAkoBL7n7osj634E3Ag48DEwwt0LE/YJMpk7TJ0apvFr2hReew0uuijZraqTVq8Ow+mfckqyWyLxKCkJl3zECvPVq8uHeaNGIbi7doVLLz04zI+q4oheTZpAnz5hieYOGzeWD/8VK+D990PFNHoYrg4dYv8KOOGEUFWtbZXOMGVmWcAnwIVAPjAXuNrdl0Zt81tgt7vfZ2bdgInuPtjMOgD/AHq4+z4zex6Y6e6PH+49Y80wJRXs3AmjR4c5WgcPDr83jz022a2qU0pKYNas0PkoMg0vAwfCD38YTl3oR09yucOmTSEso4O8NMwLow4HGzYMwd25c/kg79IlhGpVwzzRCgvDZ6j4R2DFCtixo2y7hg1Dm2P9EWjRonptqO4MU/2BVe6+JrKzZ4FhwNKobXoAvwZw9+Vmlmtm7aLeo7GZHQCygY1H9jHkS/Pnw7e/DevWhQlA7rgjOYcJddSuXTB9Ovzv/4Z/aO3ahdEemjaFiRPDV5eTAz/4QThv3aZNslucGXbtgrlzwxFw6fLZZ2XrGzSAk04KQThkSPkwz8lJfpgfTqNG0LNnWKK5h8nYKob/xx+Hkb+Lisq2PeaYMFnbrFmJr/3HE/QdgPVRj/OBARW2WQhcDvzDzPoDHYEcd59vZg8B/wL2AbPcfVasNzGzUcAogBNOOKFKHyJjuIeJuG+/PRy95+XBWWclu1V1xurV4cLfqVPDD55+/cIPnW99K4QIwNixMHNmOMq/++5wOuM73wnVr4o/1eXIFRXBkiXlQ33p0rLyxsknw4UXhv9G3buXhXm6Ha+YhQA/5hg4++zy6w4cCOcUov8AfPFFDZ3gdffDLsC3CHX50sffBf63wjbNgD8BC4AnCOWd3kBL4E2gLVAfeBm4trL3/OpXv+pSwdat7l//uju4X3aZ+7ZtyW5RnVBS4j5rlvull7qbuder537NNe7vvVf5axcvdh892j07O3yt55zj/sIL7gcO1Hy7001+vvuLL7rffrv7oEHuTZqE7xTcW7VyHzrU/Re/cP/rX/W/bk0B5vkhMjWeI/p84PioxzlUKL+4+05gBICZGbA2slwMrHX3gsi6l4AzgSeR+P3jH2Gmp82bYdy4UGROlX5dNWTPHnjiiXBkvmwZtG0L994bTlscd1x8+zjlFJg0CX71K3jssfBr4Iorwgmzm2+GG2+EVq1q9nOkoj17wrV40UfrGzaEdfXrh4nJvve9MPPkgAGhHJPh/7sm36H+AnjZ0Xo9YA3QCWhAKNOcUmGbFkCDyP2RwPTI/QHAEkJt3oBpwJjK3lNH9BFFRe6//KV7VpZ7587u8+Ylu0VJt2aN+09+4t6iRTha/MpX3KdNcy8srP6+i4rcZ8xwP++8sO/Gjd1HjnRftKj6+05VRUXuH3/s/uij4bvo1cv9qKPKjtZPOin8gho/PvyKSsR/BzkyHOaIvtKgD6/nEkLPm9XAPZHnRgOjI/fPAFYCy4GXgJZRr70v8vxiQlmnYWXvp6B3940b3QcPDv+JrrnG/fPPk92ipCkpcZ89233YsFCeycpy//a33d95J6yrCYsWhWBr1Cj8Jzj/fPeXXw7Bl842bQqf8667wmdu2rQs1Fu0cL/oIvef/cz91Vfdt2xJdmsl2uGCvtLulcmQ8d0rX38drrsudFP4/e/DlH4Z+Nt3794wL8qECWEirNatw+jK3/9+OHFXG7ZtC0P3T5wYLp/PzYVbbgmliZYta6cNNWXvXvjww/IlmH/9K6yrVw969y4rvwwYEE6Y1uWeL5nucN0rFfR1yYEDYVq/3/wm9NN67rmMHG3y00/hD38Iozn8+98hcMaODeO0JWvckaKi0B1uwgR4++1wVeR114XeOqnwn2jLFli0qGxZuDB08SsuDus7diwL9NNPD3X2dBjjJZMo6FPBp5+GE67vvgujRsH//E9IkwzhDn//ewjSGTPCc5dfHs47n3VW3fpBs2BB6KP/1FOhO9yFF4Z2XnJJ8o94CwvDyenSQP/443C7eXPZNu3bw6mnhgFNS8O9XbtD71NSg4K+rnvpJbjhhnAp55Qp4YqeDLFvX7i4d8KEcJTZqlW4iOkHPwi9X+qygoLwq+MPfwi9Tk46KZR1RoyA5s1r9r3dw3gv0UfpixaFvtilR+mNGoWeRb16lS2nnhp6KEn6UdDXVYWFcNttoQDct28o1Zx4YrJbVSvy80NATpkS6uCnnhqOiq+5JvV+yBw4EH6FTJgA77wTxkq5/vpQ1unatfr73707nKOoeJQefWl9bm75MO/VK1xVWk/DFmYMBX1d9Mkn4ch9wQL48Y/h178uu3wzTbmHEQAnTIAXXwyPhw0LAT9oUN0qzxyp+fNDWeeZZ8KQuEOGhM938cWVl3VKSsKVkhWP0levLtumadOyIC9devas+V8QUvcp6OuaJ54IXUcaNYJp0+BrX0t2i2pUYWH4sTJhQujl0aJFuBjp5pvDkWg62rw5/FqZNCkM3NWlSzjCv/76ENbbt5cdmUff7t0bXn/UUeE1FcsuHTsm/zyA1E0K+rpi9+5QxJ02Dc45J5zNq61+grVk166DB3B6661Qz+7RIxzdXnttKG9kgv37w6+XCRPgvfdCyDdvHkpXpVq3Lh/ovXqF7yrVSliSXNUdvVISYeHCUKr55BP4+c9DN8oULaAWF4eBM2MNybppU9l2Rx0VjtgHDQpDE5x/fnqUZ6qiQYPQmerqq+GDD+CPfww9dXr3LjtKb98+874XqV2pmTSpxD38fv/xj0OXktmz4bzzkt2quGzfHjvMV60qPyVbq1bhpOPFF5cfX/ukk8L42xL07x8WkdqmoK9JO3aEYvSLL4azctOmhfFK65ADB8LJvliBvnVr2Xb16pWfxSc60DWeu0jdpqCvKe+9Fy7l3LAB/vu/4Sc/SdpZNPdwZWSsMF+zpqzfNYS/Q127wje+EW5L58Ps1CllK00iGU//dGvC734Hd94ZTrT+/e/hmvIEcg/ndXfsCMu//112P3opKAinBFasgM8/L3t96XRmvXqFSTkSOZ2ZiNQ9CvpEW7gwXAQ1bBg8/njM5HQPY3pXDOZDBXaspaTk8M04+uhQO+/cOVyEVBcmKBaR5FDQJ9jmP7/HU/yIje3uY8dtTQ8Z1NHlkliaNAl/I0qX9u3DlGvRz5UuLVuWf9ysmSa+FpEyCvoEWbIEHn4Ynnz8e+ynPtlPlg/fdu3KSiOVBXXz5gpqEUkcBX01uMMbb4SAf+01aNzYubH+NG79+hq6/N+vkt08EREAdDH1Efjii9BTsk8fuOiiMFzNAw/A+pmLmfjFSLoMS4EBykUkY+iIvgq2b4fJk8OkT5s2hasa//SncNVjw4bAuNlhw0GDktpOEZFoCvo4rFoF48aFUN+7N1wBOm0aXHBBhUvX8/LC5aDHH5+kloqIHExBfwjuYWzx3/0uTCFXvz585zthJIOePWO8oKQkzDF3+eW13lYRkcNR0FdQVBRGLHj44TAIVatWcM89YUjdY489zAsXLQod4c89t7aaKiISl7hOxprZEDNbYWarzOzOGOtbmtkMM1tkZh+YWc/I813NbEHUstPMbk3wZ0iInTvDNK2dO4eRC/797zAD0vr1cP/9lYQ8hLINqD4vInVOpUf0ZpYFTAQuBPKBuWb2irsvjdrsbmCBuw83s26R7Qe7+wqgT9R+NgAzEvsRqudf/wpjhT/ySAj7c84Jjy+9tIpD06g+LyJ1VDxR1h9Y5e5r3H0/8CwwrMI2PYDZAO6+HMg1s4rzyg8GVrv7p9Vsc0LMmxeGBjjxxHCi9ZJLYO5cmDMHLrusiiFfWp/X0byI1EHxxFkHYH3U4/zIc9EWApcDmFl/oCNQceqkq4BnDvUmZjbKzOaZ2byCgoI4mlV1JSXwyishj/v1g1dfhVtvDSM4PvNMmJ/7iHz8serzIlJnxRP0sea+qTj/4INASzNbAIwBPgKKvtyBWQPgMuD/DvUm7j7F3fu6e9+2bdvG0az47d0b+r937x7GGlu3Lpxszc+Hhx4Kg3xVi+rzIlKHxdPrJh+ILjznABujN3D3ncAIADMzYG1kKTUU+NDdN1ertVX02WcwcWKY4GnbtnAU/+yz8M1vJnhs9by8UAOq9l8MEZHEiyfu5gJdzKwT4WTqVcA10RuYWQtgb6SGfyPwdiT8S13NYco2ibZ4cehB8+STYQalYcPCvB8DB9bA3JwlJaGwP3x4gncsIpIYlQa9uxeZ2S3A60AWMNXdl5jZ6Mj6yUB3YLqZFQNLgRtKX29m2YQeOzfVQPuj2hkGGPvd7+D116Fx4zCL3623hkk2aozq8yJSx8VVwHD3mcDMCs9Njrr/LhAzTt19L9C6Gm2My65doSTTpEkYYOymm6B1jb8rqs+LSJ2XNlfGNmsGs2eH6fEaNqzFN1Z9XkTquLQaprhfv1oOefWfF5EUkFZBX+sWLw5jF6s+LyJ1mIK+OlSfF5EUoKCvjrw86NQJOnZMdktERA5JQX+kSvvPq2wjInWcgv5IqT4vIilCQX+kVJ8XkRShoD9Sqs+LSIpQ0B8J1edFJIUo6I9EaX1eZRsRSQEK+iMxZ064VdCLSApQ0B+JvDzIzQ2LiEgdp6CvKtXnRSTFKOirasmSMF2Vgl5EUoSCvqrUf15EUoyCvqpUnxeRFKOgrwrV50UkBSnoq6K0Pq+yjYikEAV9VZT2n9cRvYikEAV9VeTlhbFtVJ8XkRQSV9Cb2RAzW2Fmq8zszhjrW5rZDDNbZGYfmFnPqHUtzOwFM1tuZsvM7IxEfoBao/q8iKSoSoPezLKAicBQoAdwtZn1qLDZ3cACd+8FXAeMj1o3HnjN3bsBvYFliWh4rVu6FLZuVdCLSMqJ54i+P7DK3de4+37gWWBYhW16ALMB3H05kGtm7cysGXAO8Fhk3X5335Goxteq0v7zCnoRSTHxBH0HYH3U4/zIc9EWApcDmFl/oCOQA5wIFAB/MrOPzOxRM2tS7VYng+rzIpKi4gl6i/GcV3j8INDSzBYAY4CPgCKgHvAVYJK7nwbsAQ6q8QOY2Sgzm2dm8woKCuJsfi1RfV5EUlg8QZ8PHB/1OAfYGL2Bu+909xHu3odQo28LrI28Nt/d349s+gIh+A/i7lPcva+7923btm3VPkVNU31eRFJYPEE/F+hiZp3MrAFwFfBK9AaRnjUNIg9vBN6OhP9nwHoz6xpZNxhYmqC21x6NbyMiKaxeZRu4e5GZ3QK8DmQBU919iZmNjqyfDHQHpptZMSHIb4jaxRjgqcgfgjXAiAR/hpo3Zw6ccILq8yKSkioNegB3nwnMrPDc5Kj77wJdDvHaBUDfI29ikrmHI/pLLgGLdbpCRKRu05WxlVF9XkRSnIK+Muo/LyIpTkFfmbw81edFJKUp6A+ntD5/7rmqz4tIylLQH47q8yKSBhT0h6P+8yKSBhT0h5OXB8cfD506JbslIiJHTEF/KO5l49uoPi8iKUxBfyjLlkFBgerzIpLyFPSHov7zIpImFPSHovq8iKQJBX0s6j8vImlEQR+L6vMikkYU9LGoPi8iaURBH0teHuTkqD4vImlBQV+R+s+LSJpR0Fe0fDls2aKyjYikDQV9RarPi0iaUdBXVFqfP/HEZLdERCQhFPTR1H9eRNKQgj6a6vMikoYU9NFUnxeRNBRX0JvZEDNbYWarzOzOGOtbmtkMM1tkZh+YWc+odevM7GMzW2Bm8xLZ+ITLy4MOHVSfF5G0UmnQm1kWMBEYCvQArjazHhU2uxtY4O69gOuA8RXWn+fufdy9bwLaXDNUnxeRNBXPEX1/YJW7r3H3/cCzwLAK2/QAZgO4+3Ig18zaJbSlNW3FCtXnRSQtxRP0HYD1UY/zI89FWwhcDmBm/YGOQE5knQOzzGy+mY061JuY2Sgzm2dm8woKCuJtf+KoPi8iaSqeoI9Vx/AKjx8EWprZAmAM8BFQFFk30N2/Qij93Gxm58R6E3ef4u593b1v27Zt42p8QpXW5086qfbfW0SkBtWLY5t84PioxznAxugN3H0nMALAzAxYG1lw942R2y1mNoNQCnq72i1PpNL6/AUXqD4vImknniP6uUAXM+tkZg2Aq4BXojcwsxaRdQA3Am+7+04za2JmTSPbNAEuAhYnrvkJsmIFbN6sso2IpKVKj+jdvcjMbgFeB7KAqe6+xMxGR9ZPBroD082sGFgK3BB5eTtgRjjIpx7wtLu/lviPUU2qz4tIGoundIO7zwRmVnhuctT9d4EuMV63BuhdzTbWPNXnRSSN6crY0vr8oEGqz4tIWlLQqz4vImlOQT9nTrhV0ItImlLQ5+XBccdB587JbomISI3I7KDX+DYikgEyO+g/+QQ++0xlGxFJa5kd9Oo/LyIZQEGv+ryIpLnMDXr1nxeRDJG5Qa/6vIhkiMwNevWfF5EMkblBn5cH7dtDl4OG6BERSSuZGfTqPy8iGSQzg37lSti0SWUbEckImRn06j8vIhkkc4Ne9XkRyRCZF/Sqz4tIhsm8oC+tzw8alOyWiIjUiswLetXnRSTDZF7Qz5kDxx4LJ5+c7JaIiNSKzAp61edFJAPFFfRmNsTMVpjZKjO7M8b6lmY2w8wWmdkHZtazwvosM/vIzF5NVMOPyKpVsHGjyjYiklEqDXozywImAkOBHsDVZtajwmZ3AwvcvRdwHTC+wvqxwLLqN7eaVJ8XkQwUzxF9f2CVu69x9/3As8CwCtv0AGYDuPtyINfM2gGYWQ7wNeDRhLX6SOXlqT4vIhknnqDvAKyPepwfeS7aQuByADPrD3QEciLrxgG3AyWHexMzG2Vm88xsXkFBQRzNqiLV50UkQ8UT9LFS0Ss8fhBoaWYLgDHAR0CRmV0KbHH3+ZW9ibtPcfe+7t63bdu2cTSrikrr8+o/LyIZpl4c2+QDx0c9zgE2Rm/g7juBEQBmZsDayHIVcJmZXQI0ApqZ2ZPufm0C2l41qs+LSIaK54h+LtDFzDqZWQNCeL8SvYGZtYisA7gReNvdd7r7Xe6e4+65kde9mZSQhxD07dpB165JeXsRkWSp9Ije3YvM7BbgdSALmOruS8xsdGT9ZKA7MN3MioGlwA012Oaqcw8XSqk+LyIZKJ7SDe4+E5hZ4bnJUfffBQ47FKS75wF5VW5hIqxeDRs2qGwjIhkpM66MVX1eRDJY5gS96vMikqHSP+jVf15EMlz6B73q8yKS4dI/6Evr87pQSkQyVGYE/THHQLduyW6JiEhSpHfQq/+8iEiaB/2aNZCfr/q8iGS09A569Z8XEcmAoFd9XkQyXPoGvfrPi4gA6Rz0qs+LiADpHPTqPy8iAqR70LdtC927J7slIiJJlZ5Br/q8iMiX0jPo165VfV5EJCI9g17950VEvpS+Qa/6vIgIkI5Br/q8iEg56Rf0a9fC+vUq24iIRKRf0Ks+LyJSTlxBb2ZDzGyFma0ysztjrG9pZjPMbJGZfWBmPSPPN4o8XmhmS8zsvkR/gIOoPi8iUk6lQW9mWcBEYCjQA7jazHpU2OxuYIG79wKuA8ZHnv8CON/dewN9gCFmdnqC2n6w0vr8oEGqz4uIRMRzRN8fWOXua9x9P/AsMKzCNj2A2QDuvhzINbN2HuyObFM/snhimh6D6vMiIgeJJ+g7AOujHudHnou2ELgcwMz6Ax2BnMjjLDNbAGwB/ubu71ezzYc2Z064VdCLiHwpnqCPVQOpeFT+INAyEuhjgI+AIgB3L3b3PoTg719avz/oTcxGmdk8M5tXUFAQZ/MryMuDNm2gR8XKkohI5oon6POB46Me5wAbozdw953uPiIS6NcBbYG1FbbZAeQBQ2K9ibtPcfe+7t63bdu28bY/egfqPy8iEkM8QT8X6GJmncysAXAV8Er0BmbWIrIO4EbgbXffaWZtzaxFZJvGwAXA8oS1PtoXX8AFF8Dw4TWyexGRVFWvsg3cvcjMbgFeB7KAqe6+xMxGR9ZPBroD082sGFgK3BB5eXtgWqTnzlHA8+7+ag18DmjUCB57rEZ2LSKSysy95jrBHKm+ffv6vHnzkt0MEZGUYWbz3b1vrHXpd2WsiIiUo6AXEUlzCnoRkTSnoBcRSXMKehGRNKegFxFJcwp6EZE0Vyf70ZtZAfBpsttRTW2ArcluRB2h76I8fR/l6fsoU53voqO7xxw/pk4GfTows3mHungh0+i7KE/fR3n6PsrU1Heh0o2ISJpT0IuIpDkFfc2ZkuwG1CH6LsrT91Gevo8yNfJdqEYvIpLmdEQvIpLmFPQiImlOQZ9AZna8mb1lZsvMbImZjU12m5ItMjn8R2ZWMxPOpJDITGwvmNnyyP8jZyS7TclkZj+K/DtZbGbPmFmjZLepNpnZVDPbYmaLo55rZWZ/M7OVkduWiXgvBX1iFQE/cffuwOnAzWaW6TOVjwWWJbsRdcR44DV37wb0JoO/FzPrAPwQ6OvuPQmz112V3FbVusc5eA7tO4HZ7t4FmB15XG0K+gRy903u/mHk/i7CP+QOyW1V8phZDvA14NFktyXZzKwZcA7wGIC773f3HUltVPLVAxqbWT0gG9iY5PbUKnd/G9he4elhwLTI/WnANxLxXgr6GmJmucBpwPtJbkoyjQNuB0qS3I664ESgAPhTpJT1qJk1SXajksXdNwAPAf8CNgGfu/us5LaqTmjn7psgHDgCxyRipwr6GmBmRwMvAre6+85ktycZzOxSYIu7z092W+qIesBXgEnufhqwhwT9LE9FkdrzMKATcBzQxMyuTW6r0peCPsHMrD4h5J9y95eS3Z4kGghcZmbrgGeB883syeQ2KanygXx3L/2F9wIh+DPVBcBady9w9wPAS8CZSW5TXbDZzNoDRG63JGKnCvoEMjMj1GCXufvDyW5PMrn7Xe6e4+65hJNsb7p7xh6xuftnwHoz6xp5ajCwNIlNSrZ/AaebWXbk381gMvjkdJRXgP+I3P8P4M+J2Gm9ROxEvjQQ+C7wsZktiDx3t7vPTF6TpA4ZAzxlZg2ANcCIJLcnadz9fTN7AfiQ0FvtIzJsKAQzewY4F2hjZvnAfwIPAs+b2Q2EP4bfSsh7aQgEEZH0ptKNiEiaU9CLiKQ5Bb2ISJpT0IuIpDkFvYhImlPQi4ikOQW9iEia+38FAznUw4fVqQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "# 결과 시각화\n",
    "acc = h1.history[\"accuracy\"]\n",
    "val_acc = h1.history[\"val_accuracy\"]\n",
    "loss = h1.history[\"loss\"]\n",
    "val_loss = h1.history[\"val_loss\"]\n",
    "\n",
    "e = range(1, len(acc) + 1)\n",
    "\n",
    "plt.plot(e, acc, \"-\", color=\"red\", label=\"train_acc\")\n",
    "plt.plot(e, val_acc, \"-\", color=\"blue\", label=\"test_acc\")\n",
    "plt.legend()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.legend.Legend at 0x27020489780>"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXoAAAD4CAYAAADiry33AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAi4UlEQVR4nO3deXhV1b3G8e+PEAiToMwQBZTZKdAIKDJpi4ADYq9TqxWnSItWb6sV+1h9tPWRq9bxIhS9oAVbBypDVQS1WBQQBI3KZAkIJEQFQZCAQQPr/rESM3AgJ+Ek+5x93s/z5MnJOXvvs3Ig7177t9de25xziIhIeNUJugEiIlKzFPQiIiGnoBcRCTkFvYhIyCnoRURCrm7QDYikRYsWrmPHjkE3Q0QkYaxYseIr51zLSK/FZdB37NiR5cuXB90MEZGEYWabDvWaSjciIiGnoBcRCTkFvYhIyMVljV5Ewuf7778nLy+PwsLCoJuS0NLS0khPTyc1NTXqdRT0IlIr8vLyaNKkCR07dsTMgm5OQnLOsX37dvLy8ujUqVPU66l0IyK1orCwkObNmyvkj4CZ0bx58yofFSnoRaTWKOSPXHU+w/AE/b598OCD8MYbQbdERCSuhCfo69WDBx6A6dODbomISFwJT9CbweDB8PbboJupiEgFO3fu5Mknn6zyeiNGjGDnzp1VXm/06NHMmDGjyuvVhPAEPfig37wZNm4MuiUiEmcOFfT79+8/7HqvvfYazZo1q6FW1Y5wDa8cPNh/f/ttqMLQIxGpZbfcAtnZsd1mRgY8+ughXx43bhzr168nIyOD1NRUGjduTNu2bcnOzmb16tVceOGF5ObmUlhYyM0330xWVhZQOvdWQUEBw4cP58wzz2Tx4sW0b9+e2bNn06BBg0qb9tZbb3HrrbdSVFTEaaedxsSJE6lfvz7jxo1jzpw51K1bl6FDh/LQQw/x0ksvcc8995CSkkLTpk1ZuHDhEX804erR9+wJLVr4oBcRKWP8+PGccMIJZGdn8+CDD7Js2TLuu+8+Vq9eDcCUKVNYsWIFy5cv5/HHH2f79u0HbWPdunWMHTuWVatW0axZM/7xj39U+r6FhYWMHj2aF154gU8++YSioiImTpzIjh07mDlzJqtWreLjjz/mzjvvBODee+9l3rx5fPTRR8yZMycmv3u4evQV6/QayiUSnw7T864tffr0KXfR0eOPP87MmTMByM3NZd26dTRv3rzcOp06dSIjIwOAH/3oR2yMokz86aef0qlTJ7p27QrAVVddxYQJE7jxxhtJS0vjuuuu49xzz+W8884DoH///owePZpLLrmEiy66KAa/adh69KA6vYhEpVGjRj88fvvtt3nzzTdZsmQJH330Eb169Yp4UVL9+vV/eJySkkJRUVGl7+MOMTikbt26LFu2jJ/+9KfMmjWLYcOGATBp0iT+9Kc/kZubS0ZGRsQji6oKV48eVKcXkYiaNGnC7t27I762a9cujj76aBo2bMjatWt57733Yva+3bt3Z+PGjeTk5NC5c2emTZvGoEGDKCgoYO/evYwYMYJ+/frRuXNnANavX0/fvn3p27cv//znP8nNzT3oyKKqwhf0JXX6BQvg6quDbo2IxInmzZvTv39/TjrpJBo0aEDr1q1/eG3YsGFMmjSJU045hW7dutGvX7+YvW9aWhpTp07l4osv/uFk7JgxY9ixYwcjR46ksLAQ5xyPPPIIALfddhvr1q3DOcfZZ5/NqaeeesRtsEMdVgQpMzPTHdEdpi6+GJYuhU2bVKcXiRNr1qyhR48eQTcjFCJ9lma2wjmXGWn58NXowZdvcnPhs8+CbomISODCG/SgYZYiUuPGjh1LRkZGua+pU6cG3axywlejh/Lj6a+5JujWiEiITZgwIegmVCqcPXrNeyMi8oNwBj3AkCGq04uIEOagV51eRAQIc9D36AEtWyroRSTphTfoVacXkTKqOx89wKOPPsrevXsPu0zHjh356quvqrX9mhbeoAeNpxeRH9R00MezcA6vLFG2Tn/88UG2RETKCGA6+nLz0f/kJz+hVatWvPjii+zbt49Ro0Zxzz33sGfPHi655BLy8vLYv38/f/jDH/jyyy/Jz89nyJAhtGjRggULFlTalocffpgpU6YAcN1113HLLbdE3Pall14acU76WAt30Jet02s8vUhSGz9+PCtXriQ7O5v58+czY8YMli1bhnOOCy64gIULF7Jt2zbatWvHq6++CvjJzpo2bcrDDz/MggULaNGiRaXvs2LFCqZOncrSpUtxztG3b18GDRrEhg0bDtp2yZz0a9euxcyqdcvCaIQ76DU/vUhcCno6+vnz5zN//nx69eoFQEFBAevWrWPAgAHceuut3H777Zx33nkMGDCgytt+9913GTVq1A/TIF900UW88847DBs27KBtFxUVRZyTPtbCXaMH1elF5CDOOe644w6ys7PJzs4mJyeHa6+9lq5du7JixQpOPvlk7rjjDu69995qbTuSSNs+1Jz0sZYcQQ8aZimS5MrOR3/OOecwZcoUCgoKANiyZQtbt24lPz+fhg0bcsUVV3DrrbfywQcfHLRuZQYOHMisWbPYu3cve/bsYebMmQwYMCDitgsKCti1axcjRozg0UcfJTvWJy6Khbt0A6rTiwhQfj764cOH87Of/YzTTz8dgMaNGzN9+nRycnK47bbbqFOnDqmpqUycOBGArKwshg8fTtu2bSs9Gdu7d29Gjx5Nnz59AH8ytlevXsybN++gbe/evTvinPSxFs756Cu65BJ47z3NTy8SIM1HHzuajz4S1elFJImFv3QDpXX6BQs0nl5Ejkjfvn3Zt29fueemTZvGySefHFCLKhdV0JvZMOAxIAV42jk3vsLrPwduL/6xAPilc+6jaNatFWXr9NdeW+tvLyKecw5L8PLp0qVLA33/6pTbKy3dmFkKMAEYDvQELjeznhUW+wwY5Jw7BfgjMLkK69Y8zXsjEri0tDS2b99eraASzznH9u3bSUtLq9J60fTo+wA5zrkNAGb2PDASWF3mzReXWf49ID3adWvN4MHw0kuwYQOccEKtv71IsktPTycvL49t27YF3ZSElpaWRnp6euULlhFN0LcHcsv8nAf0Pczy1wJzq7qumWUBWQDHHXdcFM2qorLj6RX0IrUuNTWVTp06Bd2MpBTNqJtIBbWIx15mNgQf9CX1+qjXdc5Nds5lOucyW7ZsGUWzqqhHD2jVShdOiUjSiaZHnwccW+bndCC/4kJmdgrwNDDcObe9KuvWCs17IyJJKpoe/ftAFzPrZGb1gMuAOWUXMLPjgJeBK51z/6nKurVq8GDIy/N1ehGRJFFpj945V2RmNwLz8EMkpzjnVpnZmOLXJwF3Ac2BJ4uHThUVl2EirltDv0vlVKcXkSSUHFMglHAO2rSBoUNh2rTYb19EJCCaAqGExtOLSBJKrqAH1elFJOkkZ9CDhlmKSNJIvqDv3l3j6UUkqSRf0KtOLyJJJvmCHlSnF5GkkrxBDyrfiEhSSM6gV51eRJJIcga96vQikkSSM+ihtE6/fn3QLRERqVHJHfSg8o2IhF7yBr3q9CKSJJI36FWnF5EkkbxBDzBkCGzZojq9iIRacge96vQikgSSO+i7dYPWrRX0IhJqyR30qtOLSBJI7qAHH/Sq04tIiCnoVacXkZBT0KtOLyIhp6BXnV5EQk5BD6rTi0ioKehBdXoRCTUFPahOLyKhpqAH1elFJNQU9CVUpxeRkFLQl1CdXkRCSkFfoqROv2BB0C0REYkpBX0J1elFJKQU9GUNHgz5+ZCTE3RLRERiRkFflur0IhJCCvqyunWDNm0U9CISKgr6slSnF5EQUtBXpDq9iISMgr4i1elFJGQU9BV17ao6vYiESlRBb2bDzOxTM8sxs3ERXu9uZkvMbJ+Z3VrhtY1m9omZZZvZ8lg1vMaoTi8iIVNp0JtZCjABGA70BC43s54VFtsB/Bp46BCbGeKcy3DOZR5JY2uN6vQiEiLR9Oj7ADnOuQ3Oue+A54GRZRdwzm11zr0PfF8Dbax9qtOLSIhEE/TtgdwyP+cVPxctB8w3sxVmlnWohcwsy8yWm9nybdu2VWHzNUB1ehEJkWiC3iI8V5XidX/nXG986WesmQ2MtJBzbrJzLtM5l9myZcsqbL4GqE4vIiESTdDnAceW+TkdyI/2DZxz+cXftwIz8aWg+Kc6vYiERDRB/z7Qxcw6mVk94DJgTjQbN7NGZtak5DEwFFhZ3cbWKtXpRSQkKg1651wRcCMwD1gDvOicW2VmY8xsDICZtTGzPOA3wJ1mlmdmRwGtgXfN7CNgGfCqc+71mvplYkp1ehEJibrRLOScew14rcJzk8o8/gJf0qnoG+DUI2lgYCrW6S3SqQoRkfinK2MPR3V6EQkBBf3hlNTpdXtBEUlgCvrDUZ1eREJAQX84Gk8vIiGgoK/MkCHw+eewbl3QLRERqRYFfWU0nl5EEpyCvjJdukDbtgp6EUlYCvrKqE4vIglOQR+NwYNVpxeRhKWgj4bq9CKSwBT00VCdXkQSmII+GqrTi0gCU9BHS3V6EUlQCvpoqU4vIglKQR8t1elFJEEp6KOlOr2IJCgFfVWoTi8iCUhBXxWq04tIAlLQV4Xq9CKSgBT0VaE6vYgkIAV9VZXU6f/zn6BbIiISFQV9ValOLyIJRkFfVV26QLt2CnoRSRgK+qpSnV5EEoyCvjoGD4YvvlCdXkQSgoK+OlSnF5EEoqCvjs6dVacXkYShoK8O1elFJIEo6KtLdXoRSRAK+upSnV5EEoSCvrpUpxeRBKGgry7V6UUkQSjoj4Tq9CKSABT0R0J1ehFJAKEK+ueeg82ba/ENVacXkQQQmqDftQtuuMFn7w03wMaNtfCmqtOLSAIITdA3bQpr1sD118Mzz/hJJq+7DjZsqOE3Vp1eROJcVEFvZsPM7FMzyzGzcRFe725mS8xsn5ndWpV1Y+nYY2HCBFi/Hn75S5g+Hbp2hauvhpycGnpT1elFJM5VGvRmlgJMAIYDPYHLzaxnhcV2AL8GHqrGujGXng6PP+578zfdBM8/D927w1VX1UDHu6ROv2BBjDcsIhIb0fTo+wA5zrkNzrnvgOeBkWUXcM5tdc69D3xf1XVrUrt28Mgj8NlncPPN8NJL0KMHXHEFrF0bozdRnV5E4lw0Qd8eyC3zc17xc9GIel0zyzKz5Wa2fNu2bVFuPjpt2sCf/+wD/7e/hZkzoWdPuPxyWL06Bm8wZAh8+SV8+mkMNiYiElvRBL1FeC7armvU6zrnJjvnMp1zmS1btoxy81XTujU88IAfkfO738E//wknnQSXXgqffHIEG1adXkTiWDRBnwccW+bndCA/yu0fybo1pmVLGD/eB/4dd8DcuXDKKfBf/wUff1yNDZ5wArRvr6AXkbgUTdC/D3Qxs05mVg+4DJgT5faPZN0a16IF3HefD/w//AHeeANOPRVGjYIPP6zChlSnF5E4VmnQO+eKgBuBecAa4EXn3CozG2NmYwDMrI2Z5QG/Ae40szwzO+pQ69bUL1NdxxwD997rA//uu/0Amt69YeRIWLEiyo0MHqw6vYjEJXNx2APNzMx0y5cvD+z9d+3ywzMfeQS+/hrOPRfuugv69DnMSjk5/iqtiRNhzJhaa6uICICZrXDOZUZ6LTRXxsZS06a+lLNxoy/tLFkCffvC8OHw3nuHWEl1eonCokXw739DUVHQLZFkoqA/jKOOgt//3gf+/ffD++/D6afD0KH+D7Yc1enlMLZuhcsugzPP9P9NWrf2F/C9/DLs2RN06yTsFPRRaNIExo3zgf/AA5Cd7f9gf/xjWLiwzIKq00sFzsG0af5CvZdfhnvu8RfujRgBc+bAT3/qBwWcfz48/bT/7yMSawr6KmjcGG67zV949ec/w8qVMGiQv17q7bfReHopZ9MmX+77xS+gWzffQbjrLj+Md9o038t/6y3IyvLXcVx/PbRtC/37+w6F+gsSKzoZewT27oXJk+F//sdPYDlwoOOuVZdx1tmGvfB80M2TgOzf7yfX+/3v/c/33w+/+hWkpBx6Hef8NRyzZ8OsWaXDe7t1gwsv9CPA+vaFOuqahdY33/hO5KmnVm/9w52MVdDHwLff+sPu8eMhPx/OSF3GoN+exnEdjA4doEMHOO44f0Qg4bZ6NVx7rT9pf8458Je/+H//qtq82Zd2Zs/2B4hFRb6uf8EFPvTPPhvS0mLefKlFubnw7rv+fN+iRX5H36KF7zRapDkFKqGgryWFhTDl2kU88bdjyKnbnaKi8v9axxxTGvpldwAlj1u2rN4/sATvu+/8jv5Pf/LndB591E+eF4t/z5074bXXfOjPnQu7d0OjRn5HcuGFfvjvMccc+ftIzdm/35fnFi0qDffc4lnAGjWCfv38eb/+/f1OvDpHbgr62rRxI3Tpwv4u3fn8iRlsbtCNTZt8vXbzZn54vGkTFBSUXzUtrTT4K37v0MGP3qxXL5DfSg5j6VJ/k5uVK/3Imsceg1ataua99u3zF/TNnu17/Pn5viQ0YIDv6Y8cCZ061cx7S/QKCvz/i5Le+pIlfgcNflbdklA/80w//Urdukf+ngr62vbWW/Dzn/ui2xNPwDXXHNS1c8731CruAMo+rjgCw8z/JzncUUGTJrX3a1bknC8xVPxq2ND3WsJmzx64804f7O3a+Wvlzj+/9t7/wAF/5fasWT74VxVfc37KKaWh37u3jhJrw5YtpaG+aJE/8b5/v//sTzqpNNj79/d/pzXxb6KgD8KXX/pj9zffhJ/9DCZNqnIKFxb6w7tD7Qxyc+H7CncAaNasNPTbtvXP7d8fOYAjfVVl2YrLHzgQ+feoV88PI8zK8qOUwhA8b77pR8ls3OgvhB4/3l9oF6T1633gz57tywMHDvi7rpXU9QcN0hFhLBw44HeqZcswJfeobtDAnzQv6a336+f/JmuDgj4o+/f7BLjrLn/l7IsvQkZGzDZ/4IA/cXOoHcEXX/haX0qKPzQ83Feslom03Kef+uGEu3b5WztmZfmLhVq0iNlHUWt27PD3NHjmGf+7PPUUDBwYdKsO9tVX8MorPvTnzfMDBpo29eP3R470wz6POiroViaGvXth2bLS3vrixf7/MvgT5GV76716QWpqMO1U0Adt4UJ/l5Pt2+Hhh/0NbcPQra2CvXthxgw/CmXxYt+zvOgiuOGGxOjlO+fbf9NNPkR/9zu//06EkS979/ojkNmz/T0Ytm3zO+DmzX0PNC3Nfy/7ONJzVXm94rL168f/v3GJL74oX4b54IPSKSt69iztrffvD8cfHz+/l4I+Hmzb5ruxc+f6K2aeeqr2junizMqV/tf/61/9eYquXX0ZZPTo+Ozl5+fD2LG+Ft67tx9K26tX0K2qnv37/dDPuXP9f8lvv/UlwrLfD/V4377qv6+ZD/yKO4K0NN8DTkkpPRKM9P1wr8VimW++8R2QRYt8CQz8zqlPn9Le+hlnxPfoJgV9vDhwwF9Se8cd/gzqCy/AaacF3arAlPTyJ0/2f2AlvfysLH+RcdA9Jed8qN92mw+5e+6B3/wmNiMkEtGBA/5ziGanUNnrJY8LCw8+31P2e6TnKlu2uhPGtWhRvgzTu7cP+0ShoI83S5b4cXiff+6vdb/55uBTLWCrVvnAL+nld+lSWsuvoTtLHlZOjj/KePttv9OZPNm3SRLDgQNV2znUrw8dOyb2n6GCPh7t2OGHXc6e7YdFTJ0a38eFteTbb0tr+YsW+cP6klp+bfTyi4r8aZS77/ZHGA895K901dQDEu80H308OuYYmDnTX0I5d64fjbN4cdCtClyDBnDllX7Y2sqVfo6YefPgrLP8vC8PPugnA6sJ2dl+aNztt/urTlev9r16hbwkOv0XDpKZL9ssXuy7rgMH+hnSDjUgPcmceKLfD+bn+5JO69Z+tEt6uq98/etfsfmoCgv9BGSZmZCX50fBzpzpr0QWCQMFfTzIzPRjuEaN8hPfn3uuHxIhQGkv/513fC1/7FiYP9/PCdKtmz/NUd1e/jvv+NkC77/fv8eaNXDxxYldqxWpSEEfL5o29V3JJ5/0k5lkZPh7zkk5PXv6e/lu2eIvwmrTxpda0tPh0kv97BPR9PK/+caXhQYO9BOSzZun0yQSXgr6eGLmL6Z67z0/OcxZZ8Ef/+iHBkg5DRr4GSbK9vLfeMPf9auyXv4rr/iy0KRJcMstflbBoUNrtfkitUpBH48yMvxsVZdd5i+/POccf7meRFTSy8/Ph+nT/Rw/Jb38Sy4p7eVv3eovUD7/fH8AtWSJX0/3CZCw0/DKeOYcTJnir7tv0gSee853WaVSa9b4se/PPgtff+2nGtq505ds7rzTnwrRBF8SJhpemajM/CDuZcv8ZXtDh/qUqu6lf0mkR4/yvfxjj/VXOn74oT9IUshLMlGPPlHs2eN79lOn+rtM/O1vvjYhIoJ69OHQqJEv4/z1r34oZkaGv7+ciEglFPSJ5sorYflyfzXPuef6K4gq3n1ERKQMBX0i6t7dD8G84QY/J8DAgf5OIyIiESjoE1WDBn4g+PPP+4HkGRl+wnQRkQoU9Inu0kt9zf744/0UCrfccmR3iBCR0FHQh0Hnzn5itJtugsce83dNKLlNjogkPQV9WNSvD48/Di+/7EO+d28/d04cDp8VkdqloA+bUaP8VUE9eviyzuDBfj5fBb5I0lLQh1HHjrBwoS/jrFvn5/MdNMhP+qLAF0k6CvqwqlcPfv1r2LDBl3TWr/fz5AwcCG++qcAXSSIK+rBLS/MnadevhyeegM8+g5/8xE+j8MYbCnyRJBBV0JvZMDP71MxyzGxchNfNzB4vfv1jM+td5rWNZvaJmWWbmSawCUpaGtx4I+TkwP/+L2zc6CdJO/NMf7smBb5IaFUa9GaWAkwAhgM9gcvNrGeFxYYDXYq/soCJFV4f4pzLONSEO1KL0tL8XTrWr/d3s9q82c9337+/Al8kpKLp0fcBcpxzG5xz3wHPAyMrLDMS+Kvz3gOamVnbGLdVYql+fX83q5wcmDjR3xX7nHPgjDP8ffUU+CKhEU3Qtwdyy/ycV/xctMs4YL6ZrTCzrEO9iZllmdlyM1u+TTfGrj3168OYMX50zqRJ/masw4bB6afD668r8EVCIJqgtwjPVfzrP9wy/Z1zvfHlnbFmNjDSmzjnJjvnMp1zmS1btoyiWRJT9ev7SdJycuAvf4HPP4fhw6FfP5g7V4EvksCiCfo84NgyP6cD+dEu45wr+b4VmIkvBUm8qlcPsrJ8D3/yZPjySxgxAvr29fPfK/BFEk40Qf8+0MXMOplZPeAyYE6FZeYAvygefdMP2OWc+9zMGplZEwAzawQMBVbGsP1SU+rVg+uvh//8B556CrZt8/Pf9+kDr76qwBdJIJUGvXOuCLgRmAesAV50zq0yszFmNqZ4sdeADUAO8BTwq+LnWwPvmtlHwDLgVefc6zH+HaQm1asH113nA//pp+Grr+C883zgv/KKAl8kAeiesVI1338P06bBfff5q25/9CO4+24f/hbpVI2I1AbdM1ZiJzUVrrkG1q7197D9+mu44ALIzIQ5c9TDF4lDCnqpntRUuPpqH/hTp8KuXTBypO/hz56twBeJIwp6OTKpqTB6tA/8Z56B3bvhwgv9fPizZinwReKAgl5io25duOoqWLMGnn0W9uzxc+P36uVr+mvXQlFR0K0USUo6GSs1o6gI/v53+OMf/Zh88CN4uneHE08s/TrpJOjUCVJSgm2vSII73MlYBb3UrP37/R2vVq0q/7VpU+kyaWn+jlglwV+yE+jQAerooFMkGocL+rq13RhJMikpfkROZoX/f7t3w+rVpcG/ciUsWADTp5cu06gR9Ox58BFAerqGcopUgXr0El927jy4979ypZ+KocRRR5XuAMoeAbRtqx2AJC2VbiTxbd9ePvhLHn/1VekyzZqVD/6SHUGrVoE1W6S2qHQjia95c3+/24EVJj/durV88K9aBS+84I8MSrRo4UO/Vy+//oAB/jmRJKEevYSPc36a5Yq9/+xsKCz0y5x4YumOY+BAaNcu0CaLHCmVbkQA9u2D5cvh3/+GhQth0SIoKPCvde5cGvqDBvkRP6r3SwJR0ItEUlTke/kLF/rwf+cdP3cPwLHHlu/xd+um4Je4pqAXicaBA77Es3BhafiXjPZp1ap88J98ssb4S1xR0ItUh3P+qt6ywb95s3+tWTN/Urck+Hv39tNAiAREQS8SK5s2lQb/woX+hizgL+7q3780+Pv08ffhFaklCnqRmvLFF+WD/5NP/PP16/sbq5cE/+mn+52BSA1R0IvUlh074N13S0f2fPCBr/3XreungRg4EE44ARo2hAYN/Peyjys+l5qqk8ASFQW9SFC++QaWLCmt8S9b5m/HGK2UlOh2CNG8XvG5tDR/5FG/fuljnWdIWLoyViQoRx0F55zjv8BfsLV9O3z7Lezd678iPY7muV27fOmo4nL79lW/vXXqRN4BRPo5mseVLdewoZ+k7uijY/N5S0QKepHalJYG7dvX7Hvs3+93KJXtMAoL/U5h376qPd6zx++sSp6vuNx331W9zU2b+vsSRPrq2NHvEKTaFPQiYZOS4k/8BnXy98ABH/bR7jQ2b4bPPvNfa9fC66/7nVFZrVodekdw3HH+XIYckoJeRGKrpPyTluZ76lXlnL9QrST8S742bvTnOGbMKH9byjp1fPmn4lFAyeN27YK/uM05fxRVUOC/du8ufVz255QU+NWvYv72OhkrIomlqAi2bDl4R1DylZ9ffvl69fzcRYc6ImjevPzIJuf8Ecehwri6P0eTtS1b+hlZq0EnY0UkPOrW9cHdoQMMHnzw64WF/sK2jRsP3gmsWOHPL5TVuDG0aVO+x33gQHRtqVMHmjTx22jcuPRxu3blny/72uF+rqFym4JeRMIlLc1PQtetW+TXd+8+eAewdasP2YoBXFk4p6UlxHUOCnoRSS5NmsApp/ivJKHp90REQk5BLyIScgp6EZGQU9CLiIScgl5EJOQU9CIiIaegFxEJOQW9iEjIxeVcN2a2DdgUdDuOUAvgq6AbESf0WZSnz6M8fR6ljuSz6OCcaxnphbgM+jAws+WHmmAo2eizKE+fR3n6PErV1Geh0o2ISMgp6EVEQk5BX3MmB92AOKLPojx9HuXp8yhVI5+FavQiIiGnHr2ISMgp6EVEQk5BH0NmdqyZLTCzNWa2ysxuDrpNQTOzFDP70MxeCbotQTOzZmY2w8zWFv8fOT3oNgXJzP67+O9kpZn93czSgm5TbTKzKWa21cxWlnnuGDN7w8zWFX8/OhbvpaCPrSLgt865HkA/YKyZ9Qy4TUG7GVgTdCPixGPA68657sCpJPHnYmbtgV8Dmc65k4AU4LJgW1XrngGGVXhuHPCWc64L8Fbxz0dMQR9DzrnPnXMfFD/ejf9Dbh9sq4JjZunAucDTQbclaGZ2FDAQ+D8A59x3zrmdgTYqeHWBBmZWF2gI5AfcnlrlnFsI7Kjw9Ejg2eLHzwIXxuK9FPQ1xMw6Ar2ApQE3JUiPAr8DDgTcjnhwPLANmFpcynrazBoF3aigOOe2AA8Bm4HPgV3OufnBtioutHbOfQ6+4wi0isVGFfQ1wMwaA/8AbnHOfRN0e4JgZucBW51zK4JuS5yoC/QGJjrnegF7iNFheSIqrj2PBDoB7YBGZnZFsK0KLwV9jJlZKj7kn3POvRx0ewLUH7jAzDYCzwNnmdn0YJsUqDwgzzlXcoQ3Ax/8yerHwGfOuW3Oue+Bl4EzAm5TPPjSzNoCFH/fGouNKuhjyMwMX4Nd45x7OOj2BMk5d4dzLt051xF/ku1fzrmk7bE5574Acs2sW/FTZwOrA2xS0DYD/cysYfHfzdkk8cnpMuYAVxU/vgqYHYuN1o3FRuQH/YErgU/MLLv4ud87514LrkkSR24CnjOzesAG4OqA2xMY59xSM5sBfIAfrfYhSTYVgpn9HRgMtDCzPOBuYDzwopldi98ZXhyT99IUCCIi4abSjYhIyCnoRURCTkEvIhJyCnoRkZBT0IuIhJyCXkQk5BT0IiIh9/+/ltcR6fve7QAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.plot(e, loss, \"-\", color=\"red\", label=\"train_loss\")\n",
    "plt.plot(e, val_loss, \"-\", color=\"blue\", label=\"test_loss\")\n",
    "plt.legend()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "예측"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[1.4017828e-05, 1.9895117e-07, 5.5150230e-07, 5.9753149e-09,\n",
       "        7.8609906e-07, 8.2428375e-07, 9.9998081e-01, 3.4380346e-10,\n",
       "        2.7642916e-06, 1.1042121e-08]], dtype=float32)"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pred = model1.predict(X_test[100:101])\n",
    "\n",
    "pred"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "6"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_test[100]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.image.AxesImage at 0x270243bafd0>"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAPsAAAD4CAYAAAAq5pAIAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAOH0lEQVR4nO3dX4xUZZrH8d+jDKIMEVha7UhHZokXkkmGGUs0QQgqi8CNzAXLYDK6/oMLSUYdshL2YvQOd3fE1ayEnh0yuLAOkFGGC3UhZFDwglgaUFyyq2sQGFu6WS6mx0RZ5NmLPmxa7Hqru86pOtU8309Sqarz1OnzUPSvz6l669Rr7i4Al77Lym4AQGsQdiAIwg4EQdiBIAg7EMSYVm5sypQpPm3atFZuEgjl2LFjOn36tA1VyxV2M1so6Z8kXS7pX9x9Xerx06ZNU7VazbNJAAmVSqVmreHDeDO7XNI/S1okaYak5WY2o9GfB6C58rxmnyXpY3f/xN3PSvqtpHuKaQtA0fKE/XpJJwbdP5kt+wYzW2FmVTOr9vX15dgcgDzyhH2oNwG+9dlbd+9294q7Vzo6OnJsDkAeecJ+UlLXoPtTJX2Wrx0AzZIn7O9IutHMvmdmYyX9RNKuYtoCULSGh97c/ZyZrZL07xoYetvk7h8W1hmAQuUaZ3f31yS9VlAvAJqIj8sCQRB2IAjCDgRB2IEgCDsQBGEHgmjp+exovaeffjpZ37x5c7K+ffv2ZD11SiXaC3t2IAjCDgRB2IEgCDsQBGEHgiDsQBAMvV0C9u3bV7O2cePG5Lrjx49P1ut9GzBDb6MHe3YgCMIOBEHYgSAIOxAEYQeCIOxAEIQdCIJx9lGgv78/WV+6dGnN2n333Zdc95lnnknWzYac/RejEHt2IAjCDgRB2IEgCDsQBGEHgiDsQBCEHQiCcfZRYMOGDcn6uHHjatZWr16dXHfMGH4Fosj1P21mxyT1S/pa0jl355sMgDZVxJ/1O9z9dAE/B0AT8ZodCCJv2F3SbjN718xWDPUAM1thZlUzq/b19eXcHIBG5Q37bHf/kaRFkh41s7kXP8Ddu9294u6Vjo6OnJsD0KhcYXf3z7LrXkmvSppVRFMAitdw2M1svJlNuHBb0gJJR4pqDECx8rwbf62kV7PzncdI+jd3f6OQrvAN9c45X7lyZc1aZ2dn0e1glGo47O7+iaQfFNgLgCZi6A0IgrADQRB2IAjCDgRB2IEgOL+xDdT7quizZ88m6zfddFOR7eASxZ4dCIKwA0EQdiAIwg4EQdiBIAg7EARhB4JgnL0NvPFGvjODFy5cWFAnuJSxZweCIOxAEIQdCIKwA0EQdiAIwg4EQdiBIBhnbwP1pmQeO3Zsss5MOxgO9uxAEIQdCIKwA0EQdiAIwg4EQdiBIAg7EATj7C3g7sn6mTNnkvX58+cX2U7b2LdvX7K+bdu2XD9/4sSJNWtz5sxJrrto0aJkPZuqfFSpu2c3s01m1mtmRwYtm2xme8zso+x6UnPbBJDXcA7jfyPp4q9CWSNpr7vfKGlvdh9AG6sbdnd/S9LFx5n3SNqc3d4saUmxbQEoWqNv0F3r7j2SlF1fU+uBZrbCzKpmVu3r62twcwDyavq78e7e7e4Vd69wwgZQnkbDfsrMOiUpu+4triUAzdBo2HdJuj+7fb+k3xfTDoBmqTvObmYvS5onaYqZnZT0C0nrJG03s4ckHZe0tJlNjnY9PT3J+uHDh5P1J598ssh2ClVv7vg1a2oP1Kxfvz657g033JCsT5gwIVnv6uqqWXvxxReT6+7YsSNZX7BgQbLejuqG3d2X1yjdVXAvAJqIj8sCQRB2IAjCDgRB2IEgCDsQBKe4jgJlfvLw/PnzyfojjzySrL/00ks1a/W+QvuBBx5I1q+44opkPWXnzp3J+sqVK5P1Q4cOJetXX331CDtqPvbsQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAE4+wt8Omnn+Za/5Zbbimok5FbtWpVsr579+5kfc+ePTVrd92VPnGymV/XfPfddyfrX375ZbL+xRdfJOuMswMoDWEHgiDsQBCEHQiCsANBEHYgCMIOBME4ewv09rbvHBqff/55sr5r165kfevWrcn6nXfeOeKeWuHKK69M1qdPn56s79+/P1lftmzZiHtqNvbsQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAE4+wtMHbs2FzrnzhxIlnPc+70li1bkvVTp04l67Nnz25426NZf39/2S2MWN09u5ltMrNeMzsyaNlTZvZHMzuUXRY3t00AeQ3nMP43khYOsXy9u8/MLq8V2xaAotUNu7u/JelMC3oB0ER53qBbZWbvZ4f5k2o9yMxWmFnVzKp9fX05Ngcgj0bDvkHSdEkzJfVI+mWtB7p7t7tX3L1S5gSFQHQNhd3dT7n71+5+XtKvJM0qti0ARWso7GbWOejujyUdqfVYAO2h7ji7mb0saZ6kKWZ2UtIvJM0zs5mSXNIxSenJrIO7/fbbk/XrrrsuWd+4cWOy/sILL4y4pwtuu+22ZP3cuXPJ+ptvvpmsL1iwYMQ9tUK9f1e9cfSJEycW2E1r1A27uy8fYvGvm9ALgCbi47JAEIQdCIKwA0EQdiAIwg4EwSmuLTBhwoRkferUqcn6jh07kvX169fXrI0Zk/4vnjx5crJeb9rkekNY7er5559P1ut9xXa96abbEXt2IAjCDgRB2IEgCDsQBGEHgiDsQBCEHQiCcfY2sHr16mT93nvvTdYff/zxmrV6p7/OmDEjWX/44Ydz1R988MGatXHjxiXXrWfOnDnJ+vHjx2vW1q5dm1z39ddfT9YnTar5TWxtiz07EARhB4Ig7EAQhB0IgrADQRB2IAjCDgTBOHsbWLZsWbL+yiuvJOvd3d01a1dddVVy3SeeeCJZr3fe9+LF6Ql8T58+XbPm7sl1v/rqq2S93vNy+PDhmrW33347ue7NN9+crI9G7NmBIAg7EARhB4Ig7EAQhB0IgrADQRB2IAjG2UeBLVu2JOupc7OfffbZ5Lrbtm1L1pcsWZKsd3V1JespO3fuTNYPHDiQrM+fPz9Zf+6552rWZs6cmVz3UlR3z25mXWb2BzM7amYfmtnPsuWTzWyPmX2UXY++s/mBQIZzGH9O0s/d/SZJt0l61MxmSFojaa+73yhpb3YfQJuqG3Z373H397Lb/ZKOSrpe0j2SNmcP2yxpSZN6BFCAEb1BZ2bTJP1Q0kFJ17p7jzTwB0HSNTXWWWFmVTOr9vX15WwXQKOGHXYz+66k30l6zN3/NNz13L3b3SvuXuno6GikRwAFGFbYzew7Ggj6Vne/cKrRKTPrzOqdknqb0yKAIli90wxtYM7ezZLOuPtjg5b/g6T/cfd1ZrZG0mR3/9vUz6pUKl6tVvN3jWE7ePBgsl5v6G3//v3J+tGjR5P1efPm1azVO4107ty5yfodd9yRrF92WbyPkVQqFVWr1SHn2R7OOPtsST+V9IGZHcqWrZW0TtJ2M3tI0nFJSwvoFUCT1A27ux+QNORfCkmjb0Z6IKh4xzlAUIQdCIKwA0EQdiAIwg4EwSmul7hbb701Vx2XDvbsQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAEYQeCIOxAEIQdCIKwA0EQdiAIwg4EQdiBIAg7EARhB4Ig7EAQhB0IgrADQRB2IAjCDgRB2IEgCDsQRN2wm1mXmf3BzI6a2Ydm9rNs+VNm9kczO5RdFje/XQCNGs4kEeck/dzd3zOzCZLeNbM9WW29u/9j89oDUJThzM/eI6knu91vZkclXd/sxgAUa0Sv2c1smqQfSjqYLVplZu+b2SYzm1RjnRVmVjWzal9fX75uATRs2GE3s+9K+p2kx9z9T5I2SJouaaYG9vy/HGo9d+9294q7Vzo6OvJ3DKAhwwq7mX1HA0Hf6u6vSJK7n3L3r939vKRfSZrVvDYB5DWcd+NN0q8lHXX3Zwct7xz0sB9LOlJ8ewCKMpx342dL+qmkD8zsULZsraTlZjZTkks6JmllE/oDUJDhvBt/QJINUXqt+HYANAufoAOCIOxAEIQdCIKwA0EQdiAIwg4EQdiBIAg7EARhB4Ig7EAQhB0IgrADQRB2IAjCDgRh7t66jZn1Sfp00KIpkk63rIGRadfe2rUvid4aVWRvN7j7kN//1tKwf2vjZlV3r5TWQEK79taufUn01qhW9cZhPBAEYQeCKDvs3SVvP6Vde2vXviR6a1RLeiv1NTuA1il7zw6gRQg7EEQpYTezhWb2n2b2sZmtKaOHWszsmJl9kE1DXS25l01m1mtmRwYtm2xme8zso+x6yDn2SuqtLabxTkwzXupzV/b05y1/zW5ml0v6L0l/JemkpHckLXf3/2hpIzWY2TFJFXcv/QMYZjZX0p8lveTu38+W/b2kM+6+LvtDOcndn2yT3p6S9Oeyp/HOZivqHDzNuKQlkv5GJT53ib7+Wi143srYs8+S9LG7f+LuZyX9VtI9JfTR9tz9LUlnLlp8j6TN2e3NGvhlabkavbUFd+9x9/ey2/2SLkwzXupzl+irJcoI+/WSTgy6f1LtNd+7S9ptZu+a2YqymxnCte7eIw388ki6puR+LlZ3Gu9Wumia8bZ57hqZ/jyvMsI+1FRS7TT+N9vdfyRpkaRHs8NVDM+wpvFulSGmGW8LjU5/nlcZYT8pqWvQ/amSPiuhjyG5+2fZda+kV9V+U1GfujCDbnbdW3I//6+dpvEeappxtcFzV+b052WE/R1JN5rZ98xsrKSfSNpVQh/fYmbjszdOZGbjJS1Q+01FvUvS/dnt+yX9vsRevqFdpvGuNc24Sn7uSp/+3N1bfpG0WAPvyP+3pL8ro4caff2lpMPZ5cOye5P0sgYO6/5XA0dED0n6C0l7JX2UXU9uo97+VdIHkt7XQLA6S+rtdg28NHxf0qHssrjs5y7RV0ueNz4uCwTBJ+iAIAg7EARhB4Ig7EAQhB0IgrADQRB2IIj/A181NVN4p6uQAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# 이미지로 출력하려면 1차원 데이터를 다시 2차원으로 변경\n",
    "img = X_test[100].reshape(28, 28)\n",
    "\n",
    "plt.imshow(img, cmap=plt.cm.binary)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(784,)\n",
      "(28, 28)\n"
     ]
    }
   ],
   "source": [
    "print(X_test[100].shape)\n",
    "print(img.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([6], dtype=int64)"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pred_class = model1.predict_classes(X_test[100:101])\n",
    "pred_class"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "학습된 모델을 저장"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "model1.save(\"./mnist_model.h5\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "직접 손으로 숫자를 쓴 다음 인식을 해보자"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 저장된 모델을 불러오기\n",
    "from tensorflow.keras.models import load_model\n",
    "\n",
    "model2 = load_model(\"./mnist_model.h5\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "손글씨를 불러오기"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.image.AxesImage at 0x2701a999f98>"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAASAAAAD8CAYAAADXCHlgAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAArmElEQVR4nO3dd3RU1b7A8e9v0qmhBAgkShFF2qUXRRFQA6KA8rgPFGHx9GEBvIKIFEFAiIICUkQflktsIF7q0gsIeClSpYRuFFQgtBAgQCAhbb8/MtEMJw0yJZn8PmtlzfA7c87+Zdbkx55z9tlbjDEopZQn2DydgFKq5NICpJTyGC1ASimP0QKklPIYLUBKKY/RAqSU8hiXFSAR6SwiMSJyRERGuqodpVTxJa4YByQiPsAvwENALPAT0McYc8jpjSmlii1X9YBaAUeMMb8ZY1KAhUB3F7WllCqmfF103BrAiWz/jgVa5/biypUrm5o1a7ooFaWUJ/3xxx/Ex8dLTttcVYByaszhu56IDAQGAtx2223s3LnTRakopTypRYsWuW5z1VewWCA827/DgFPZX2CMmWeMaWGMaRESEuKiNJRSRZmrCtBPQF0RqSUi/kBvYIWL2lJKFVMu+QpmjEkTkcHAasAH+NQYc9AVbSmlii9XnQPCGPNv4N+uOr5SqvjTkdDKLXTeKZUTl/WAlAK4fv0669ev5+DBg1SpUoWIiAj0ooPKogVIuUxiYiJz585lypQpXLhwgYCAAPr168f777+Pn5+fp9NTRYB+BVMukZyczJQpU5gwYQIXLlwAMntDK1asYPfu3R7OThUV2gNSTpeYmMisWbN47733uHbtmmW7SI6DYlUJpAVIOdX169d59913mTJlCsnJyZbtHTt2pFGjRh7ITBVFWoCUUxhjOHr0KHPmzOGTTz6xFB+bzUa3bt2IjIwkKCjIQ1mqokYLkHKKAwcOMGDAAHbt2pXj9oiICGbPnk1YWJibM1NFmZ6EVoV27Ngx3njjjRxPLosIPXv2ZO7cuVp8lIX2gNQtS01NZfXq1UyfPp3169dbBhuKCBEREcyYMYPw8PBcjqJKMi1A6pYcOHCAuXPn8vnnn5OYmJjja3r27Mm0adO0+KhcaQFSNyU5OZmlS5cSGRnJwYMHc73Fon79+rz99tvcdtttbs5QFSdagFSBJSUlMWPGDCIjI7l69Wqur/Pz8+P555+ndu3absxOFUdagFSBJCQkMHXqVGbPnp1n8QGoXr067du31wGHKl9agFS+zp8/zxtvvMGHH35Ienp6vq9v1qyZDjZUBaIFSOUpNjaWV199lSVLlhSo+NhsNvr06aO9H1UgWoBUro4dO8bQoUNZtmxZgefzqV27Nm3btnVxZspbaAFSFsYYDh48yHPPPce2bdssxcdmyxy/mpGR4RD38/Ojf//+VKtWzW25quJNR0Iri3379vG///u/bN26NcciU7p06Rx7RM2bN+d//ud/8PXV/9dUwWgBUg7OnDmTa8+ndOnStGvXDhGxbAsNDWXKlClUr17dnemqYk4LkPpTUlIS06dPz/GervLlyzNixAjKly/P5cuXHbYFBgYybNgw2rRp465UlZfQAqT+tGrVKubOnUtqaqpDPCQkhMjISNq1a8fmzZst+3Xt2pUXX3wRf39/d6WqvIQWIAXAkSNHmDhxomWQYbly5ZgyZQp9+vThs88+Iz4+3mF7WFgYL7/8MqVKlXJnuspLFKoAicgfIrJfRKJFZKc9VlFE1ojIr/bHCs5JVbnKtWvXiIyMZN++fQ5xEeHpp5+mX79+xMTEsGTJEodzPyJC165dadmypbtTVl7CGT2gDsaYJsaYrBXoRwLrjDF1gXX2f6siKiMjg3/9618sWLDAcsXr3nvvZdiwYaSlpTFnzhyuXLnisL1ixYq88MILBAQEuDNl5UVc8RWsOxBlfx4F9HBBG8pJ9u/fz1tvvWWZQjU4OJixY8dSu3Zttm7dytq1ay379uzZk7vvvttdqSovVNgCZIDvRWSXiAy0x6oaY04D2B+rFLIN5SKXL19mwoQJxMTEOMQDAgIYMmQIDzzwAImJicycOZOzZ886vCY8PJwBAwboiWdVKIUdMXavMeaUiFQB1ojIzwXd0V6wBgI6Z4wHpKamMn/+fL799lvLmJ527dr9eVVr+fLlrFq1yrJ/586dadasmbvSVV6qUD0gY8wp+2McsBRoBZwVkVAA+2NcLvvOM8a0MMa00KV63csYw/z585kwYYLlknu1atWIjIykWrVq/PHHHzkurxMWFsZLL72kvR9VaLdcgESktIiUzXoOPAwcAFYA/e0v6w8sL2ySynkyMjJYtWoV48eP/3PF0ixBQUEMHTqUpk2bkp6eTlRUlOXKmL+/Py+88AL16tVzZ9rKSxXmK1hVYKl92gVf4CtjzCoR+QlYJCLPAMeBXoVPUznLpk2bGDx4MKdOnbJs69GjBy+88AJ+fn5ER0fz/vvvW3pIrVq14tlnn9X7vZRT3PKnyBjzG/C3HOLngU6FSUo5nzGGvXv38o9//IPffvvNYZvNZuOhhx5i0qRJlC1blkuXLjF16lTLoMMyZcowYsQIqlTR6wrKOXQkdAnx22+/MWjQIMtXKoAmTZowe/bsP+dw3rZtm+XktIjQq1cvOnTo4LaclffTAlQCxMbGMnjwYLZu3Wq54tW4cWPef/996tatC2T2lJYtW2YZdFirVi2GDx9OmTJl3Ja38n5agLxccnIyU6dOZe3atTlOoTFt2jRat279Z+zq1ausX7/ecpx+/fpRv359V6erShgtQF5u7dq1fPzxx6SlpTnEQ0NDmT17Nh07dnSYv3n37t2WQYfBwcE88sgjbslXlSxagLzYiRMneOedd0hKSnKIBwUFMWnSJLp16/bn9KpZtm7davn6Vb9+fWrUqOHyfFXJowXIS6WlpfHBBx+wZcsWh7iPjw8DBw7kqaeews/Pz2HbpUuX2LJli0NvSURo2bKlzvOsXEILkJfasWNHjl+9GjVqxODBg3O8gz0uLs4yG2JgYCDt2rWz9JSUcgb9VHmh+Ph4Jk2axLlz5xzi/v7+jBw5kjvuuCPH/fbt20dsbKxDrEyZMtx3330uy1WVbFqAvExGRgafffYZ69atc4jbbDZ69+6d58nk1atXW2Jt2rShUqVKTs9TKdAC5HV2797NjBkzSElJcYjXrFmTV199lbJly+a437lz5yzniwA6deqEj4+PS3JVSguQFzl16hRjxozh5MmTDnF/f3+GDx9OgwYNctwvLS2NqKgojhw54hCvUqUKzZs312WWlctoAfIS6enpzJgxg3Xr1lluoYiIiODvf/97roXkzJkz/N///R/Xr193iNerV48777zTpXmrkk0LkBfIyMjg66+/5uOPPyY9Pd1hW+3atXnzzTdzPY+Tnp7Op59+ytGjRx3i/v7+PP/883rjqXIpLUBe4Oeff2bixIkkJCQ4xMuUKcPo0aP5298skxb86cCBA3z55ZeW2zTatGmjo5+Vy2kBKuYuXrzI66+/bpnX2cfHh2eeeYbevXvnum9aWhpffPEFv/76q0O8fPnyDBkyhHLlyrkkZ6WyaAEqxlJSUpgzZw4rV660bGvdujUjR47Mc8HA/fv3M3/+fEvv54EHHqBz58568lm5nBagYmzDhg1Mnz7dMmdzeHg4kydPzvP2ievXrzN37lzOnz/vEA8MDGTIkCE67YZyCy1AxVRMTAyjR4+2nPcJDAxk9OjRtGvXLs/9f/zxR7777jvLFbM+ffo4TM+hlCtpASqGspZS3rVrl0NcRHj88cfp27dvnnM2JycnM2fOHE6fPu0QDwkJYcCAAdr7UW6jBaiYSU5OZvr06Xz99deWczetW7fmzTffzLOApKamMm/evBxvu+jZsyf33HOP03NWKjdagIqRrOlSZ86caRk0GBwczIQJE6hTp06ex9iyZUuOcwSFhYXx/PPP620Xyq20ABUj27Zt47XXXrOsVhEUFMTo0aN54IEH8tz/2LFjDB8+3HLHu7+/P88++6yu9aXcTgtQMXHkyBFeffVVTpw44RD38fGhV69ePP/883muVHr58mUmT55MdHS0Q1xEuO+++xg0aJCudKrcLt8CJCKfikiciBzIFqsoImtE5Ff7Y4Vs20aJyBERiRGRCFclXpJcvHiRESNGsHnzZstVqw4dOjB58uRc73KHzK9uUVFRzJ8/3zJBWd26dXnnnXeoXLmyy/JXKjcF6QHNBzrfEBsJrDPG1AXW2f+NiNQHegMN7PvMFRE9qVAI165dY8qUKXz33XeWbXXr1mXatGmEhYXlur8xhrVr1/Luu+9aVjktV64cEyZMoHHjxk7PW6mCyLcAGWM2AhduCHcHouzPo4Ae2eILjTHXjTG/A0eAVs5JtWRasGABM2fOtMzvExISwltvvZVv8Th58iSjR4/m+PHjDnFfX1+eeeYZevXqpSeelcfc6jmgqsaY0wD2x6xbpmsA2U9SxNpj6iYZY/j222+ZMGGCZaRzUFAQY8eO5bHHHsvzGJcvX2bcuHGW8UIAXbp0YcSIEVp8lEc5+yR0TjcPmRxiiMhAEdkpIjtvnLtYwS+//MKoUaMsJ519fX15+umnefbZZy2rWmSXnp5OVFQU33zzjWW80O23386bb76pK10oj7vVAnRWREIB7I9x9ngsEJ7tdWHAqZwOYIyZZ4xpYYxpERIScotpeKfY2FiGDh3KwYMHLdu6du3K+PHjCQoKyvMYmzZtYuLEiSQmJjrEK1SowNtvv02jRo2cmrNSt+JWC9AKoL/9eX9gebZ4bxEJEJFaQF1gR+FSLFnyWkq5Xr16TJo0idDQ0DyPcfToUcaOHWsZL2Sz2XjmmWfo0aOHLrOjigZjTJ4/wALgNJBKZg/nGaASmVe/frU/Vsz2+jHAUSAG6JLf8Y0xNG/e3ChjUlJSzOzZs01gYKAh86vrnz9hYWHmhx9+yPcYV69eNX379jUi4rC/iJjOnTub+Ph4N/wmSv3F/vedc33JbYM7f7QAZVq9erWpUaOGpfgEBQWZefPmmbS0tDz3zypgpUqVshzjjjvuMLt373bTb6LUX/IqQNoPLyJiYmIYNmyYZUULPz8/Bg8eTN++ffO9YrVx40YiIyO5du2aQ7xs2bK8+eabNG3a1Ol5K1UYWoCKgLNnzzJq1CgOHz7sEBcRHn74YUaNGpXvSefjx48zevRoyxQbWQWse/fuTs9bqcLKfdIY5RapqalMnz6dZcuWWU46N2rUiKlTp1KhQoVc9s6UkpLC7Nmzcxzv88ADDzB8+PB8C5hSnqA9IA9KS0vj008/Zd68eZbiExoayrvvvsvdd9+d73GOHTvGv/71L8uSPPXq1ePtt9+mYsWKTs1bKWfRAuRB27Zty3E5naCgIIYPH86DDz5YoInhly9fzh9//GE5xvjx42nSpInzElbKybQAecgvv/zC0KFDOXXKcZymzWbjueeeY+DAgQUqPqdOneLLL7+0xDt37kz37t11vI8q0vTT6QGXLl3i9ddfZ8+ePQ5xEaF9+/aMGDGiQPMyG2NYvXo1v/zyi0O8bNmyPPnkkwQGBjo1b6WcTQuQmyUnJzNjxgyWLFliOWdTv359pk+fnu9I5yxXrlwhKirKctm9RYsWdOjQwWk5K+UqWoDcKCMjg0WLFjFnzhxL8QkODmbSpEl5LqN8o61bt7Jjh+OdLj4+Pjz55JO5rgWvVFGiBciNtm/fzuuvv25ZDDAoKIhXX32VRx55pMCrkSYnJxMVFWWZXL5OnTo8+uijTstZKVfSAuQme/fu5aWXXrJMr2Gz2ejduzdDhgy5qTmZd+7cyYYNGxxiPj4+PPXUUzq9qio2tAC5QXx8PKNGjWLnzp2WbW3atGHcuHF5zul8o7S0NJYsWWK5ghYeHk6PHj3yXJRQqaJEC5CLxcfHM2LECNasWWPZVq9ePWbOnMntt99+U8c8ceIEixYtssQ7d+5Mw4YNbzlXpdxN/6t0oUuXLjFu3Di++OILy2oUISEhTJw4kRYtWtzUMY0xfPPNN5w9e9YhXrp0afr166fjflSxogXIRS5evMgrr7zCl19+aVmNolSpUkycOJHHH3/8po97/PhxvvnmG0tBe/TRR3WWQ1XsaAFyAWMMH3/8MV988YWl+Pj5+TFw4ED69+9/S+dqNmzYwP79+x1i5cqVo1evXgUavKhUUaL9dRc4duwYn332maX4ZN1mMXbs2Fu6Oz0pKYmPPvrIsi58w4YNiYjQNSBV8aM9IBc4cOCAZWIxf39/+vXrx/jx42/57vR169axd+9eh5iPjw8DBgzQ3o8qlrQH5GQJCQl8+umnXLx40SHeuHFjIiMjb3mE8pUrV/jqq68sq1w0bNiQhx566JbzVcqTtAA5UUpKClOmTOHbb7+1bGvTpg2FWX7o0KFDlpUyfH196dmzZ55LMytVlGkBcqIdO3bkeO6ndOnSdOvWrVDH/uqrr7hxAcdKlSrRp08fXd1UFVtagJwkMTGRyMhIy+jkwMBAXnrpJdq1a3fLx46JiWH58uWWeK9evahVq9YtH1cpT9MC5ARJSUl8+OGH/Oc//3GIiwhPPfUUI0eOvOU5mdPT01m2bJmlsIWEhPBf//Vf2vtRxVq+BUhEPhWROBE5kC02XkROiki0/eeRbNtGicgREYkREa+/NpySksKMGTMYP348ycnJDtvuuusuXnvtNcqVK3fLx4+Li8txPFGHDh1o3rz5LR9XqaKgID2g+UDnHOIzjDFN7D//BhCR+kBvoIF9n7ki4rX/RSclJTFr1iymTp3K1atXHbYFBQXx0ksvUbt27UK1sWrVKstyPYGBgfTt21cvvatiL98CZIzZCFwo4PG6AwuNMdeNMb8DR4BWhcivSPv6668ZN24cly5dsmx78MEHefrppwv1FenSpUt8/vnnlsnLmjdvrjMeKq9QmHNAg0Vkn/0rWtbCVTWA7BPexNpjXufMmTPMnj3bMiGYiNClSxemTZtWqB5K1uyJ27dvd4gHBATQt29fSpcufcvHVqqouNUC9AFQB2gCnAam2eM5TedncoghIgNFZKeI7Lzx8nJxEB0dbVkKB6Bjx4588MEH1K1bt1DHj4uLY9asWZb5nhs1asSjjz5a4JkTlSrKbqkAGWPOGmPSjTEZwEf89TUrFgjP9tIw4NSN+9uPMc8Y08IY06IwA/Q84cqVKyxfvtyynlezZs2YO3fuTc/vc6O0tDQ+/vhjDh065BDPupFVBx4qb3FLBUhEsi/b8DiQdYVsBdBbRAJEpBZQF9hx4/7FWdaqFvPnzycjI+PPuIjQunVr7rzzzkK3cejQIaKiohyOD9C6dWueeOKJQh9fqaIi35tRRWQB8ABQWURigTeAB0SkCZlfr/4AngMwxhwUkUXAISANGGSMSc/hsMWSMYYlS5Ywffp0yyX3gIAAp9yRnpaWxqxZszh69KhDvGLFigwfPlyXWVZeJd8CZIzpk0P4kzxePxmYXJikiqrLly8zd+5cy1UvHx8funXr5pQrU1u3bmXp0qWWteI7duzIQw89pOd+lFfRkdAFlJaWxkcffWS5KgWZt0S89957hRpwCJmX3WfOnGm5k75SpUqMGDGCUqVKFer4ShU1WoAKaOvWrcyePdsyFWqDBg2YOHFigVczzcvatWtZvXq1Q+/Hx8eHp59+WqdbVV5JC1ABXL58mTfeeIPjx487xEuVKsXgwYMLPdoZMns/U6dOtcz3Ex4ezqBBg3Sdd+WVtADlIzU1lQ8++IDNmzdbtnXt2pW+ffsW+oZQYwyff/65ZbZDX19fXnzxRerUqVOo4ytVVGkBysdPP/3ErFmzSElJcYjXqVOHUaNGOeV+rISEBP79739b5npu3rw5ffr00RPPymtpAcpDbGwsY8aMsUyFUapUKV577TUaN27slHbi4uLYs2ePQywwMJBBgwZRo4ZX3smiFKAFKFfnz59nxIgR/Pjjj5ZtERERTp2JMCYmxrLQYKVKlejatav2fpRX01UxcnDp0iXGjh3L119/bRmNXK9ePcaNG+fUqTBWrVplGffTqlUrypcv77Q2lCqKtAd0g6SkJN57770cb4UoV64cY8aMceol8eTk5BzHFrVr106XWVZeT3tA2aSlpfHPf/6TyMhIy0nnMmXKMGbMGHr37u3UaVAPHTrEmTNnHGIVK1akZcuW+vVLeT39L9YuPT2dhQsXMmHCBEvx8ff358UXX+TFF1+8peWU8/LTTz9x/vx5h1jt2rULfUe9UsWB9oDInPxr+fLlDBs2zLL0jY+PD71792bs2LFOnwI1OTmZnTt3Wi6/33XXXVSvXt2pbSlVFJX4HlBGRgYLFy5kyJAhluIjInTr1o133nnHJfMvX7lyhZ07dzrEfH19uf/++53e01KqKCrRn/Ksns8rr7xiOQ8DcM899zBt2jSqVKnikvZPnDjBzz//7BDz8/Pj/vvvd0l7ShU1JboHtGfPHoYOHZpr8Zk3b55LF/7bsGGDZV6hO++8U2c8VCVGiS5ACxYs4NixY5Z4q1atmD17NvXr13dZ2xkZGTneX3bfffcREBDgsnaVKkpK7Few2NjYHJc7bt26Nf/85z+5++67Xdr+gQMH2LVrl0MsICCAe+65Bz8/P5e2rVRRUSJ7QOnp6SxZsoSTJ086xENCQhg/frzLi096ejorVqwgNjbWIV6tWjXuuusul7atVFFSIgvQDz/8QGRkpGVNr7Zt29K2bVuXt3/hwgWioqIsk5u1bNnSpV/7lCpqSlwB2rt3LyNGjLDc/Onv788TTzzhlvuvFi9ebFlTzN/fn/79++vEY6pEKVEF6MyZMwwdOpTo6GjLtpYtW9K9e3eX53Du3DkWLVpk6f20bduWdu3aubx9pYqSElOArl27xsSJE9m4caNlW8OGDZk+fTrBwcEuz2PDhg2Wm0+DgoLo27ev3v2uSpwSUYCMMXz33XcsXLiQ9HTHZcoqVKjAW2+9RcuWLV2eR0pKCvPnz7cst1ynTh0ee+wxvflUlTj5FiARCReR/4jIYRE5KCL/sMcrisgaEfnV/lgh2z6jROSIiMSISOFX6yuk48ePM378eMtyN+XKlWPKlCl07tzZLX/827dvz7EHNmDAAKpWrery9pUqagrSA0oDXjHG3A20AQaJSH1gJLDOGFMXWGf/N/ZtvYEGQGdgrog4b/6Km5SYmMi7775rueXBZrMxYMAA+vbt65b7rpKSkvjss88sq17cfvvtPPbYYy5vX6miKN8CZIw5bYzZbX9+BTgM1AC6A1H2l0UBPezPuwMLjTHXjTG/A0eAVk7Ou0CSk5OZOnUqn3zyiWVysVatWjF8+HCCgoLcksuhQ4csMx/abDb++7//m5o1a7olB6WKmps6ByQiNYGmwHagqjHmNGQWKSDrjs0awIlsu8XaY26V1fOZMWOGZbxP5cqVGT16tNsmfDfGsHjxYsvAwypVqvD3v/9dRz6rEqvA3z1EpAywGHjZGHM5j3MmOW0wlheJDAQGAtx2220FTaNAUlNTmTZtGm+99ZZlrh0RoX///m6d8P3EiRMsWLDAEu/QoQPNmjVzSw5KFUUF6gGJiB+ZxedLY8wSe/isiITat4cCcfZ4LBCebfcwwHFdG8AYM88Y08IY0yIkJORW87fImt/nvffesxQfm81Gjx49ePnll90233JGRgaLFy+2LO0THBzMs88+q1e+VImWbw9IMv9CPgEOG2OmZ9u0AugPvG1/XJ4t/pWITAeqA3WBHc5MOi8XLlzg/fffJyEhwbItIiKCmTNnUqNGDcsqFNnlte1mxcfHs2LFCss0r/feey9/+9vfLOem1F+yirMWae9VkK9g9wJPA/tFJNoeG01m4VkkIs8Ax4FeAMaYgyKyCDhE5hW0QcaYdMtRXeDs2bOMHTvWMssgZPY47rjjDhYvXpznMRISEjh79qzTitDFixct027YbDYSEhIYM2aMU9rwVn5+ftSuXZtOnTrRoEEDpy4GoIoIY4zHf5o3b24KKyMjw3z44YcmICDAkHnOSX+85KdBgwZm27Zthf6MKM+w/33n+LfvNSOh09LSOHTokOW8jyr+Dh48yDfffGMZxa6KP68pQL6+vrRs2ZKyZct6OhXlAnquzDt5zYyIIkKPHj04efIkixYt4tSpU049l6M8p3r16nTt2lXPAXkhrylAkLl66bBhw3jyySdJTEzk6tWr/Pbbbxw/fpwLFy64NZfjx4+zYMECh/+5bTYbPXv25I477nBrLsVZYGAgDz/8MM2bN/d0KsoFvKoAQeaVk/Dwv4YhtWjRwiN5jB071tL7qlatGjNnziQ0NNQjOSlV1HjNOaCi5MyZM5b7vgCeeOIJKleu7KGslCp6tAC5wPbt2/n1118dYhUqVCAiIkLv+1IqGy1ATpaSksLy5cu5dOmSQ7xRo0Y65apSN9AC5GRxcXGsXLnSISYidO3a1S1TvipVnGgBcrKlS5dy7tw5h1ilSpXo0aOHZxJSqgjTAuREly5dYuXKlZYRuw899BDVq1f3UFZKFV1agJwoJibGsuRP6dKl6datG2XKlPFMUkoVYVqAnMQYw/r16zlz5oxDPDw8nA4dOngoK6WKNi1ATpKSksLSpUstY3/at2+vK14olQstQE4SHR3N4cOHHWL+/v706tXLQxkpVfRpAXICYwyrVq2yLLnTqFEj7rrrLg9lpVTRpwXICc6cOcPatWsdrn7ZbDY6depEtWrVPJiZUkWbFiAnOHr0KHv37nWIlS1blgcffNAtix4qVVxpAXKCJUuWcOXKFYdYrVq1aNu2rYcyUqp40AJUSImJiaxZs8YSf/TRRyldurQHMlKq+NACVEibNm3ixIkTDrHg4GAiIiJ0ORml8qEFqBBSU1NZvXo1ly9fdog3bdqUO++800NZKVV8aAEqhPj4eNavX+8w+NDHx4f27dtTpUoVD2amVPGQbwESkXAR+Y+IHBaRgyLyD3t8vIicFJFo+88j2fYZJSJHRCRGRCJc+Qt40p49e9i/f79DLOveL6VU/gpyjTgNeMUYs1tEygK7RCTrrOsMY8y72V8sIvWB3kADMpdmXisidxo3rY7qTsuWLbMsF9OoUSPuvvtuD2WkVPGSbw/IGHPaGLPb/vwKcBiokccu3YGFxpjrxpjfgSNAK2ckW5QcP36cjRs3OsRsNhtPPPEE/v7+HspKqeLlps4BiUhNoCmw3R4aLCL7RORTEalgj9UAsl8WiiXvglUsbdmyhZMnTzrEQkNDueeee7DZ9NSaUgVR4L8UESkDLAZeNsZcBj4A6gBNgNPAtKyX5rC7ZXVAERkoIjtFZOeNMwgWdUlJSaxcudJy71fjxo1p2LChh7JSqvgpUAESET8yi8+XxpglAMaYs8aYdGNMBvARf33NigXCs+0eBpy68ZjGmHnGmBbGmBYhISGF+R3c7vz58/zwww8OMZvNxiOPPKITjyl1EwpyFUyAT4DDxpjp2eLZV9d7HDhgf74C6C0iASJSC6gL7HBeyp63ZcsWTp1yrKlly5alc+fOHspIqeKpIFfB7gWeBvaLSLQ9NhroIyJNyPx69QfwHIAx5qCILAIOkXkFbZA3XQEzxvDDDz9Yrn7df//9Ou+zUjcp3wJkjPmRnM/r/DuPfSYDkwuRV5EVFxfHrl27HGI2m40OHToQFBTkoayUKp70cs1NOnToEMeOHXOIVa1alZYtW+q9X0rdJC1ANyEjI4Po6Gji4+Md4qGhoTr4UKlboAXoJqSkpLBmzRrLxPNt27alUqVKHspKqeJLC9BNuHjxIj/99JNDTETo1KmThzJSqnjTAnQTfvzxR8vUG1WrVqVZs2Yeykip4k0LUAFlZGSwadMmUlNTHeJt2rShYsWKHspKqeJNC1ABnT17ll27djmc//H19aVNmzY69apSt0gLUAEdPXqUX375xSEWHBxMmzZt9OZTpW6R/uUUgDGGPXv2cP78eYd45cqVadq0qYeyUqr40wJUABkZGXz//fc5rvterlw5D2WlVPGnBagAzp8/z+7dux1ievldqcLTAlQAmzZtIiEhwSFWo0YNGjdu7JmElPISWoDykZ6ezubNm0lKSnKIN23alKpVq3ooK6W8gxagfMTHx7Nnzx7L0jutWrUiODjYc4kp5QW0AOUjNjaW6Ohoh1jp0qW57777PJOQUl5EC1A+duzYYTn/ExISordfKOUEWoDyYIxh5cqVlvj999+vo5+VcgItQHmIi4uzrHxqs9l48MEHdfSzUk6gf0V52Lx5s2X0c3h4OA0aNPBQRkp5Fy1AuUhLS2PHjh2Wtb/q1avHbbfd5qGslPIuWoBykZCQwObNmy2X39u2bUuFChXy2FMpVVBagHJx5swZ9u3b5xDz9/fXy+9KOZEWoFxs2bIlx9kPmzdv7qGMlPI+BVkZNVBEdojIXhE5KCIT7PGKIrJGRH61P1bIts8oETkiIjEiEuHKX8AVMjIyWLNmjSXevn17SpUq5YGMlPJOBekBXQc6GmP+BjQBOotIG2AksM4YUxdYZ/83IlIf6A00ADoDc0XExwW5u0xsbKzl8ruPjw/t27fHz8/PQ1kp5X3yLUAmU9alID/7jwG6A1H2eBTQw/68O7DQGHPdGPM7cARo5cykXW3v3r2cOXPGIRYWFqZ3vyvlZAU6ByQiPvZ14eOANcaY7UBVY8xpAPtjFfvLawAnsu0ea48VC2lpaWzfvt1y/qdWrVrUrVvXQ1kp5Z0KVICMMenGmCZAGNBKRBrm8fKc1ic2lheJDBSRnSKy89y5cwVK1h0SExP57rvvHC6/iwjt2rXT2Q+VcrKbugpmjEkA1pN5buesiIQC2B/j7C+LBcKz7RYGnMrhWPOMMS2MMS1CQkJuPnMXOXToEIcPH3aI+fn5ERFR7M6lK1XkFeQqWIiIBNufBwEPAj8DK4D+9pf1B5bbn68AeotIgIjUAuoCO5yct0sYY1i0aBEpKSkO8fr169OwYV6dPqXUrfAtwGtCgSj7lSwbsMgY862IbAUWicgzwHGgF4Ax5qCILAIOAWnAIGNMumvSd67Tp0+zdetWh69fNpuNLl26UKZMGQ9mppR3yrcAGWP2AZa1Z4wx54EcZ2U3xkwGJhc6OzfbvXs3P//8s0OsUqVKdOrUCV/fgtRqpdTN0JHQdmlpaaxevdpy9atOnTq0aNHCQ1kp5d20ANklJiayatUqS7xr166UL1/eAxkp5f20ANmtX7+eEydOOMRKlSpF165dPZSRUt5PCxB/ff268epX27ZtqVmzpmeSUqoE0AIE/P777/z4448OV7+yxv7o0jtKuY4WIDLv/YqJiXGIVaxYkY4dOyKS08BupZQzlPgClJGRwZIlS0hNTXWIN2zYkKZNLaMPlFJOVOIL0KlTp9i4caNDTETo3r27rnyhlIuV+L+wtWvXWla+CA0NpUOHDh7KSKmSo0QXoMTERL7//nuSk5Md4vfeey+33367h7JSquQo0QXo5MmTbNmyxSEWEBBAx44dKVu2rIeyUqrkKNEFaMOGDRw/ftwhFhwcTJcuXTyUkVIlS4ktQBkZGaxYscJh7A9kDj4MCwvzUFZKlSwltgAdOXLEsu6Xr68vPXv2xMenWM2hr1SxVWIL0IEDB0hISHCI1alTh2bNmnkmIaVKoBJZgNLT09m9e3eO677rvV9KuU+JLEBXrlxh165dlnXfmzdvrgsPKuVGJbYA7dmzxyHm6+urE48p5WYlsgAdOXKEuLg4h1iZMmX0/I9SblYiC9CNE88DNGrUSGc+VMrN5MY/RI8kIXIOuArEezCNytq+tl9C23d127cbY3Jc/K9IFCAAEdlpjPHYSRhtX9svqe17su0S+RVMKVU0aAFSSnlMUSpA87R9bV/bL1ltF5lzQEqpkqco9YCUUiWMxwuQiHQWkRgROSIiI93U5h8isl9EokVkpz1WUUTWiMiv9scKTmzvUxGJE5ED2WK5ticio+zvR4yIRLio/fEictL+HkSLyCMubD9cRP4jIodF5KCI/MMed8t7kEf7bnkPRCRQRHaIyF57+xPscXf9/rm177bPQK6MMR77AXyAo0BtwB/YC9R3Q7t/AJVviE0FRtqfjwSmOLG9+4FmwIH82gPq29+HAKCW/f3xcUH744HhObzWFe2HAs3sz8sCv9jbcct7kEf7bnkPAAHK2J/7AduBNm78/XNr322fgdx+PN0DagUcMcb8ZoxJARYC3T2US3cgyv48CujhrAMbYzYCFwrYXndgoTHmujHmd+AIme+Ts9vPjSvaP22M2W1/fgU4DNTATe9BHu3nxtntG2NM1tQLfvYfg/t+/9zaz43TPwO58XQBqgFkX5A9lrw/GM5igO9FZJeIDLTHqhpjTkPmBxao4uIccmvPne/JYBHZZ/+KltX9d2n7IlITaErm/8Jufw9uaB/c9B6IiI+IRANxwBpjjFt//1zaBw98BrLzdAHKadlRd1yWu9cY0wzoAgwSkfvd0GZBues9+QCoAzQBTgPTXN2+iJQBFgMvG2Mu5/VSV+SQQ/tuew+MMenGmCZAGNBKRBrmlaqb2nf7Z+BGni5AsUB4tn+HAadc3agx5pT9MQ5YSmb38qyIhALYH+NyP4JT5NaeW94TY8xZ+4cyA/iIv7rYLmlfRPzI/OP/0hizxB5223uQU/vufg/sbSYA64HOeOAzkL19T/z+N/J0AfoJqCsitUTEH+gNrHBlgyJSWkTKZj0HHgYO2Nvtb39Zf2C5K/PIo70VQG8RCRCRWkBdYIezG8/64Ns9TuZ74JL2RUSAT4DDxpjp2Ta55T3IrX13vQciEiIiwfbnQcCDwM+47/fPsX13fgZy5Yoz2zd5hv4RMq9KHAXGuKG92mSe4d8LHMxqE6gErAN+tT9WdGKbC8js4qaS+b/LM3m1B4yxvx8xQBcXtf85sB/YR+YHLtSF7bcjswu/D4i2/zzirvcgj/bd8h4AjYE99nYOAOPy+8y5qX23fQZy+9GR0Eopj/H0VzClVAmmBUgp5TFagJRSHqMFSCnlMVqAlFIeowVIKeUxWoCUUh6jBUgp5TH/D2VgZ0V474bCAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import PIL.Image as pil\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# 이미지 불러오기\n",
    "# convert(\"L\") : 흑백이미지를 불러오기\n",
    "gray_img = pil.open(\"./data/n4.png\").convert(\"L\")\n",
    "\n",
    "plt.imshow(gray_img, cmap=\"gray\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(340, 388)"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 학습 데이터로 쓸려면 이미지데이터에서 배열로 변환\n",
    "arrimg = np.array(gray_img)\n",
    "\n",
    "arrimg.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[0, 0, 0, ..., 0, 0, 0],\n",
       "       [0, 0, 0, ..., 0, 0, 0],\n",
       "       [0, 0, 0, ..., 0, 0, 0],\n",
       "       ...,\n",
       "       [0, 0, 0, ..., 0, 0, 0],\n",
       "       [0, 0, 0, ..., 0, 0, 0],\n",
       "       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 원래 MNIST 데이터가 검정색 바탕에 흰색 글씨로 되어 있기때문에\n",
    "# 같은 형태로 변경하기 위해서 최대값에 빼줌\n",
    "arrimg = 255 - arrimg\n",
    "\n",
    "arrimg"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-fb1086c2cd8d>\", line 2, in <module>\n",
      "    test_img = arrimg.reshape(1, 28*28)\n",
      "ValueError: cannot reshape array of size 131920 into shape (1,784)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-fb1086c2cd8d>\", line 2, in <module>\n",
      "    test_img = arrimg.reshape(1, 28*28)\n",
      "ValueError: cannot reshape array of size 131920 into shape (1,784)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-fb1086c2cd8d>\", line 2, in <module>\n",
      "    test_img = arrimg.reshape(1, 28*28)\n",
      "ValueError: cannot reshape array of size 131920 into shape (1,784)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "# 2차원 -> 1차원\n",
    "test_img = arrimg.reshape(1, 28*28)\n",
    "\n",
    "# 0-255 -> 0.0 - 1.0 \n",
    "test_img = test_img.astype(\"float32\") / 255"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-21d352cb82eb>\", line 1, in <module>\n",
      "    pred = model2.predict(test_img)\n",
      "NameError: name 'test_img' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-21d352cb82eb>\", line 1, in <module>\n",
      "    pred = model2.predict(test_img)\n",
      "NameError: name 'test_img' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "ERROR! Session/line number was not unique in database. History logging moved to new session 328\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-21d352cb82eb>\", line 1, in <module>\n",
      "    pred = model2.predict(test_img)\n",
      "NameError: name 'test_img' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "pred = model2.predict(test_img)\n",
    "pred"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-b99f13340520>\", line 1, in <module>\n",
      "    pred_class = model2.predict_classes(test_img)\n",
      "NameError: name 'test_img' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "ERROR! Session/line number was not unique in database. History logging moved to new session 329\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-b99f13340520>\", line 1, in <module>\n",
      "    pred_class = model2.predict_classes(test_img)\n",
      "NameError: name 'test_img' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-25-b99f13340520>\", line 1, in <module>\n",
      "    pred_class = model2.predict_classes(test_img)\n",
      "NameError: name 'test_img' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "pred_class = model2.predict_classes(test_img)\n",
    "pred_class"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "베스트 모델 찾아서 저장하기"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 330\n",
      "Model: \"sequential_1\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "dense_4 (Dense)              (None, 512)               401920    \n",
      "_________________________________________________________________\n",
      "dense_5 (Dense)              (None, 256)               131328    \n",
      "_________________________________________________________________\n",
      "dense_6 (Dense)              (None, 128)               32896     \n",
      "_________________________________________________________________\n",
      "dense_7 (Dense)              (None, 10)                1290      \n",
      "=================================================================\n",
      "Total params: 567,434\n",
      "Trainable params: 567,434\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "\n",
    "model1 = Sequential()\n",
    "\n",
    "# 입력층\n",
    "model1.add(Dense(units=512, input_dim=784, activation=\"relu\"))\n",
    "\n",
    "# 은닉층\n",
    "# units의 수를 늘려가는 방법 : 인코딩 (특성을 추출, 특성을 늘려줌)\n",
    "# units의 수를 줄여가는 방법 : 디코딩 (특성을 정리, 특성을 선택)\n",
    "model1.add(Dense(units=256, activation=\"relu\"))\n",
    "model1.add(Dense(units=128, activation=\"relu\"))\n",
    "\n",
    "# 출력층\n",
    "model1.add(Dense(units=10, activation=\"softmax\"))\n",
    "\n",
    "model1.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "model1.compile(loss=\"categorical_crossentropy\",\n",
    "               optimizer=\"adam\",\n",
    "               metrics=[\"accuracy\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.callbacks import ModelCheckpoint\n",
    "import os \n",
    "\n",
    "# 베스트 모델을 저장할 폴더\n",
    "MODEL_DIR = \"./model/\"\n",
    "\n",
    "# 해당 폴더가 없다면\n",
    "if not os.path.exists(MODEL_DIR) : \n",
    "    # 폴더를 생성한다\n",
    "    os.mkdir(MODEL_DIR)\n",
    "    \n",
    "# 저장할 파일명의 형식을 저장\n",
    "# {epoch:03d} : epoch 값을 정수형 3자리로 표시, \n",
    "#               만약 3자리 안되면 앞자리는 0으로 채움\n",
    "#         -> mnist_001  or minst_010\n",
    "# {loss:.3f} : val_accuracy 값을 소수점 3째자리까지 표시\n",
    "#         -> mnist_001_0.080\n",
    "\n",
    "# mnist_001_0.080_0.070.hdf5\n",
    "filename = MODEL_DIR + \"mnist_{epoch:03d}_{loss:.3f}_{val_loss:.3f}.hdf5\"\n",
    "\n",
    "# 베스트모델 찾기\n",
    "# filepath : 저장할 위치와 파일명\n",
    "# monitor : 베스트 모델의 기준값\n",
    "# save_best_only : 현재 모델보다 기준이 더 나은 모델만 저장할 것인지 여부\n",
    "mc = ModelCheckpoint(filepath=filename,\n",
    "                     monitor=\"val_loss\",\n",
    "                     save_best_only=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 60000 samples, validate on 10000 samples\n",
      "Epoch 1/10\n",
      "60000/60000 [==============================] - 1s 22us/sample - loss: 0.2295 - accuracy: 0.9332 - val_loss: 0.1257 - val_accuracy: 0.9614\n",
      "Epoch 2/10\n",
      "60000/60000 [==============================] - 1s 19us/sample - loss: 0.0846 - accuracy: 0.9737 - val_loss: 0.0858 - val_accuracy: 0.9714\n",
      "Epoch 3/10\n",
      "60000/60000 [==============================] - 1s 25us/sample - loss: 0.0565 - accuracy: 0.9824 - val_loss: 0.0760 - val_accuracy: 0.9766\n",
      "Epoch 4/10\n",
      "60000/60000 [==============================] - 1s 17us/sample - loss: 0.0382 - accuracy: 0.9877 - val_loss: 0.0723 - val_accuracy: 0.9796\n",
      "Epoch 5/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0300 - accuracy: 0.9903 - val_loss: 0.0755 - val_accuracy: 0.9777\n",
      "Epoch 6/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0269 - accuracy: 0.9911 - val_loss: 0.0722 - val_accuracy: 0.9814\n",
      "Epoch 7/10\n",
      "60000/60000 [==============================] - 1s 22us/sample - loss: 0.0218 - accuracy: 0.9926 - val_loss: 0.1162 - val_accuracy: 0.9716\n",
      "Epoch 8/10\n",
      "60000/60000 [==============================] - 1s 17us/sample - loss: 0.0228 - accuracy: 0.9929 - val_loss: 0.0743 - val_accuracy: 0.9800\n",
      "Epoch 9/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0146 - accuracy: 0.9956 - val_loss: 0.0815 - val_accuracy: 0.9787\n",
      "Epoch 10/10\n",
      "60000/60000 [==============================] - 1s 17us/sample - loss: 0.0184 - accuracy: 0.9938 - val_loss: 0.0992 - val_accuracy: 0.9770\n"
     ]
    }
   ],
   "source": [
    "# callbacks : 리스트에 있는 콜백함수들을 epoch마다 실행\n",
    "h2 = model1.fit(X_train, y_train_en, epochs=10, batch_size=128,\n",
    "                validation_data=(X_test, y_test_en),\n",
    "                callbacks=[mc])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-c4aeed805472>\", line 1, in <module>\n",
      "    best_model = load_model(\"./model/mnist_006_0.026_0.073.hdf5\")\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow_core\\python\\keras\\saving\\save.py\", line 149, in load_model\n",
      "    loader_impl.parse_saved_model(filepath)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow_core\\python\\saved_model\\loader_impl.py\", line 83, in parse_saved_model\n",
      "    constants.SAVED_MODEL_FILENAME_PB))\n",
      "OSError: SavedModel file does not exist at: ./model/mnist_006_0.026_0.073.hdf5/{saved_model.pbtxt|saved_model.pb}\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-c4aeed805472>\", line 1, in <module>\n",
      "    best_model = load_model(\"./model/mnist_006_0.026_0.073.hdf5\")\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow_core\\python\\keras\\saving\\save.py\", line 149, in load_model\n",
      "    loader_impl.parse_saved_model(filepath)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow_core\\python\\saved_model\\loader_impl.py\", line 83, in parse_saved_model\n",
      "    constants.SAVED_MODEL_FILENAME_PB))\n",
      "OSError: SavedModel file does not exist at: ./model/mnist_006_0.026_0.073.hdf5/{saved_model.pbtxt|saved_model.pb}\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-c4aeed805472>\", line 1, in <module>\n",
      "    best_model = load_model(\"./model/mnist_006_0.026_0.073.hdf5\")\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow_core\\python\\keras\\saving\\save.py\", line 149, in load_model\n",
      "    loader_impl.parse_saved_model(filepath)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow_core\\python\\saved_model\\loader_impl.py\", line 83, in parse_saved_model\n",
      "    constants.SAVED_MODEL_FILENAME_PB))\n",
      "OSError: SavedModel file does not exist at: ./model/mnist_006_0.026_0.073.hdf5/{saved_model.pbtxt|saved_model.pb}\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "best_model = load_model(\"./model/mnist_006_0.026_0.073.hdf5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-6b17a90a2d9e>\", line 1, in <module>\n",
      "    pred = best_model.predict_classes(test_img)\n",
      "NameError: name 'best_model' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "ERROR! Session/line number was not unique in database. History logging moved to new session 331\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-6b17a90a2d9e>\", line 1, in <module>\n",
      "    pred = best_model.predict_classes(test_img)\n",
      "NameError: name 'best_model' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-29-6b17a90a2d9e>\", line 1, in <module>\n",
      "    pred = best_model.predict_classes(test_img)\n",
      "NameError: name 'best_model' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\SM2139\\anaconda3\\envs\\deep01\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "pred = best_model.predict_classes(test_img)\n",
    "pred"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "epochs 값은 얼마가 좋을까요 ? 최적의 epochs 값은 ?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 332\n",
      "Model: \"sequential_2\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "dense_8 (Dense)              (None, 512)               401920    \n",
      "_________________________________________________________________\n",
      "dense_9 (Dense)              (None, 256)               131328    \n",
      "_________________________________________________________________\n",
      "dense_10 (Dense)             (None, 128)               32896     \n",
      "_________________________________________________________________\n",
      "dense_11 (Dense)             (None, 10)                1290      \n",
      "=================================================================\n",
      "Total params: 567,434\n",
      "Trainable params: 567,434\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "\n",
    "model1 = Sequential()\n",
    "\n",
    "# 입력층\n",
    "model1.add(Dense(units=512, input_dim=784, activation=\"relu\"))\n",
    "\n",
    "# 은닉층\n",
    "# units의 수를 늘려가는 방법 : 인코딩 (특성을 추출, 특성을 늘려줌)\n",
    "# units의 수를 줄여가는 방법 : 디코딩 (특성을 정리, 특성을 선택)\n",
    "model1.add(Dense(units=256, activation=\"relu\"))\n",
    "model1.add(Dense(units=128, activation=\"relu\"))\n",
    "\n",
    "# 출력층\n",
    "model1.add(Dense(units=10, activation=\"softmax\"))\n",
    "\n",
    "model1.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "model1.compile(loss=\"categorical_crossentropy\",\n",
    "               optimizer=\"adam\",\n",
    "               metrics=[\"accuracy\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 학습이 더 이상 좋지지않으면 학습을 중단\n",
    "from tensorflow.keras.callbacks import EarlyStopping\n",
    "\n",
    "# monitor : 중단하는 중단 (좋아지지 않는다는 기준)\n",
    "# patience : 학습이 나아지지 않더라도 기다려주는 epochs 수\n",
    "es = EarlyStopping(monitor=\"val_loss\",\n",
    "                   patience=10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 60000 samples, validate on 10000 samples\n",
      "Epoch 1/10000\n",
      "60000/60000 [==============================] - 1s 24us/sample - loss: 0.2251 - accuracy: 0.9347 - val_loss: 0.1052 - val_accuracy: 0.9675\n",
      "Epoch 2/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0851 - accuracy: 0.9737 - val_loss: 0.0738 - val_accuracy: 0.9754\n",
      "Epoch 3/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0569 - accuracy: 0.9821 - val_loss: 0.0798 - val_accuracy: 0.9749\n",
      "Epoch 4/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0394 - accuracy: 0.9872 - val_loss: 0.0738 - val_accuracy: 0.9777\n",
      "Epoch 5/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0299 - accuracy: 0.9901 - val_loss: 0.0748 - val_accuracy: 0.9780\n",
      "Epoch 6/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0258 - accuracy: 0.9915 - val_loss: 0.0780 - val_accuracy: 0.9777\n",
      "Epoch 7/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0229 - accuracy: 0.9924 - val_loss: 0.0738 - val_accuracy: 0.9798\n",
      "Epoch 8/10000\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0177 - accuracy: 0.9940 - val_loss: 0.0682 - val_accuracy: 0.9835\n",
      "Epoch 9/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0158 - accuracy: 0.9946 - val_loss: 0.0890 - val_accuracy: 0.9773\n",
      "Epoch 10/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0133 - accuracy: 0.9956 - val_loss: 0.0805 - val_accuracy: 0.9814\n",
      "Epoch 11/10000\n",
      "60000/60000 [==============================] - 1s 21us/sample - loss: 0.0148 - accuracy: 0.9953 - val_loss: 0.0990 - val_accuracy: 0.9789\n",
      "Epoch 12/10000\n",
      "60000/60000 [==============================] - 1s 18us/sample - loss: 0.0129 - accuracy: 0.9958 - val_loss: 0.0885 - val_accuracy: 0.9787\n",
      "Epoch 13/10000\n",
      "60000/60000 [==============================] - 1s 19us/sample - loss: 0.0139 - accuracy: 0.9953 - val_loss: 0.0886 - val_accuracy: 0.9801\n",
      "Epoch 14/10000\n",
      "60000/60000 [==============================] - 1s 17us/sample - loss: 0.0134 - accuracy: 0.9956 - val_loss: 0.0928 - val_accuracy: 0.9795\n",
      "Epoch 15/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0090 - accuracy: 0.9975 - val_loss: 0.0777 - val_accuracy: 0.9808\n",
      "Epoch 16/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0099 - accuracy: 0.9967 - val_loss: 0.0881 - val_accuracy: 0.9817\n",
      "Epoch 17/10000\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0118 - accuracy: 0.9962 - val_loss: 0.0823 - val_accuracy: 0.9818\n",
      "Epoch 18/10000\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0072 - accuracy: 0.9978 - val_loss: 0.1061 - val_accuracy: 0.9801\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<tensorflow.python.keras.callbacks.History at 0x2702f7320b8>"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model1.fit(X_train, y_train_en, epochs=10000, batch_size=128,\n",
    "           validation_data=(X_test, y_test_en),\n",
    "           callbacks=[mc, es])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "전통적인 딥러닝의 문제점\n",
    "\n",
    "- 많은 퍼셉트론 연산으로 인해 시간이 많이 걸리는 문제 -> GPU\n",
    "- 많은 퍼셉트론을 사용하므로해서 생기는 복잡성 -> 과대적합 -> Dropout\n",
    "- 활성화함수를 sigmoid, tanhs를 사용해서 생기는 기울기소실 -> Relu"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Dropout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_3\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "dense_12 (Dense)             (None, 512)               401920    \n",
      "_________________________________________________________________\n",
      "dense_13 (Dense)             (None, 256)               131328    \n",
      "_________________________________________________________________\n",
      "dense_14 (Dense)             (None, 128)               32896     \n",
      "_________________________________________________________________\n",
      "dropout (Dropout)            (None, 128)               0         \n",
      "_________________________________________________________________\n",
      "dense_15 (Dense)             (None, 10)                1290      \n",
      "=================================================================\n",
      "Total params: 567,434\n",
      "Trainable params: 567,434\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense, Dropout\n",
    "\n",
    "model1 = Sequential()\n",
    "\n",
    "# 입력층\n",
    "model1.add(Dense(units=512, input_dim=784, activation=\"relu\"))\n",
    "\n",
    "# 은닉층\n",
    "model1.add(Dense(units=256, activation=\"relu\"))\n",
    "model1.add(Dense(units=128, activation=\"relu\"))\n",
    "\n",
    "# 퍼셉트론 중에서 50%는 사용하지 않겠다 \n",
    "# epoch마다 사용하지 않는 퍼셉트론을 다를 수 있다\n",
    "model1.add(Dropout(0.5))\n",
    "\n",
    "# 출력층\n",
    "model1.add(Dense(units=10, activation=\"softmax\"))\n",
    "\n",
    "model1.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "model1.compile(loss=\"categorical_crossentropy\",\n",
    "               optimizer=\"adam\",\n",
    "               metrics=[\"accuracy\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 60000 samples, validate on 10000 samples\n",
      "Epoch 1/10\n",
      "60000/60000 [==============================] - 1s 23us/sample - loss: 0.2926 - accuracy: 0.9125 - val_loss: 0.1135 - val_accuracy: 0.9665\n",
      "Epoch 2/10\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.1097 - accuracy: 0.9686 - val_loss: 0.0894 - val_accuracy: 0.9714\n",
      "Epoch 3/10\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0732 - accuracy: 0.9785 - val_loss: 0.0798 - val_accuracy: 0.9760\n",
      "Epoch 4/10\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0537 - accuracy: 0.9841 - val_loss: 0.0788 - val_accuracy: 0.9792\n",
      "Epoch 5/10\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0407 - accuracy: 0.9878 - val_loss: 0.0718 - val_accuracy: 0.9783\n",
      "Epoch 6/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0359 - accuracy: 0.9889 - val_loss: 0.0768 - val_accuracy: 0.9790\n",
      "Epoch 7/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0283 - accuracy: 0.9916 - val_loss: 0.0897 - val_accuracy: 0.9768\n",
      "Epoch 8/10\n",
      "60000/60000 [==============================] - 1s 15us/sample - loss: 0.0230 - accuracy: 0.9928 - val_loss: 0.0811 - val_accuracy: 0.9801\n",
      "Epoch 9/10\n",
      "60000/60000 [==============================] - 1s 16us/sample - loss: 0.0246 - accuracy: 0.9926 - val_loss: 0.0730 - val_accuracy: 0.9828\n",
      "Epoch 10/10\n",
      "60000/60000 [==============================] - 1s 18us/sample - loss: 0.0159 - accuracy: 0.9949 - val_loss: 0.0878 - val_accuracy: 0.9818\n"
     ]
    }
   ],
   "source": [
    "h4 = model1.fit(X_train, y_train_en, epochs=10, batch_size=128,\n",
    "             validation_data=(X_test, y_test_en))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.legend.Legend at 0x270347d4748>"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXoAAAD4CAYAAADiry33AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAlZ0lEQVR4nO3deXxV9Z3/8deHhCVhJ0GKwABuLGWLbEJArbQqarUuP8UWrY5IrUrRVqu2znRsxxnnMY6j7cOBolIHtagFaZ3KjOu9IovsiwgIKCgBCxFkCSZAku/vj++NNwkXcgM3OXd5Px+P+7jLOfeeby7kfb75nO/5HnPOISIi6atJ0A0QEZGGpaAXEUlzCnoRkTSnoBcRSXMKehGRNJcddANiyc/Pdz169Ai6GSIiKWP58uVfOOc6xlqWlEHfo0cPli1bFnQzRERShpl9eqxlKt2IiKQ5Bb2ISJpT0IuIpLmkrNHHcuTIEYqKiigrKwu6KSmpRYsWdO3alaZNmwbdFBFpZCkT9EVFRbRu3ZoePXpgZkE3J6U459i9ezdFRUX07Nkz6OaISCNLmdJNWVkZeXl5CvkTYGbk5eXpryGRDJUyQQ8o5E+CvjuRzJUypRsRkbTjHOzaBevXw7p1cOAA3HdfwjejoBcRaWjOwbZtPsyrQr3q/ssvo+t17gw//zkk+C9wBX2c9u7dyx//+Eduv/32er3vkksu4Y9//CPt2rVrmIaJSPIoL4dPPvEhXj3Q16+Hgwej6+XnQ9++cO21/r5PH39/6qkJD3lQ0Mdt7969/Nd//ddRQV9RUUFWVtYx3zd37tyGbpqINLZDh2DjxqN75xs3wuHD0fW6dPEBfsst0UDv0wc6xpySpsGkZtDfdResWpXYzxw0CB5//JiL77//fj7++GMGDRpE06ZNadWqFZ07d2bVqlWsW7eO733ve2zbto2ysjImT57MxIkTgei8PSUlJYwdO5ZRo0axcOFCunTpwl/+8hdycnJibu+pp55i2rRpHD58mDPOOIPnnnuO3Nxcdu7cyW233cYnn3wCwJQpUxg5ciQzZszg0UcfxcwYMGAAzz33XGK/H5FMVFICGzbU7JmvWwcffwyVlX4dMzjtNB/gl1wSDfM+faBNm2DbH5GaQR+ARx55hLVr17Jq1SrC4TCXXnopa9eu/Xpc+vTp0+nQoQOlpaUMHTqUq6++mry8vBqfsWnTJmbOnMlTTz3Ftddey+zZsxk/fnzM7V111VXceuutADz44IM888wzTJo0iZ/85Cecd955zJkzh4qKCkpKSvjwww95+OGHWbBgAfn5+ezZs6dhvwyRE1Fa6g887tzp73ftgt27ff06Oxuysvytvo9P5D21H5eV1Qz0qvvPPou2PzsbzjoLBgyAceOi5ZazzoJjdNiSRWoG/XF63o1l2LBhNU4++u1vf8ucOXMA2LZtG5s2bToq6Hv27MmgQYMAGDx4MFu3bj3m569du5YHH3yQvXv3UlJSwkUXXQTAO++8w4wZMwDIysqibdu2zJgxg2uuuYb8/HwAOnTokKgfU+TYKiv9gcSq0K4e4FWPq7924EDQLY5PTg707g2jRtWsn59+OqTomeWpGfRJoGXLll8/DofDvPXWWyxatIjc3FzOP//8mCcnNW/e/OvHWVlZlJaWHvPzb7rpJv785z8zcOBAnn32WcLh8DHXdc5pnLwkxqFDUFxcd2jv3OnXKy8/+jOaNPEHGzt1glNOgWHDoo+r7qse5+X50kdFhf+sior4Htdn3XgeN20KvXr5UO/e3f8MaURBH6fWrVtz4Bg9kn379tG+fXtyc3PZsGED77///klv78CBA3Tu3JkjR47wwgsv0KVLFwDGjBnDlClTuOuuu6ioqODgwYOMGTOGK6+8krvvvpu8vDz27NmjXr0czTnYvt0f31q92j+uHeT79sV+b05ONKS7dYPBg2sGd/UAz8vzJRFJGgr6OOXl5VFYWEi/fv3IycmhU6dOXy+7+OKLmTp1KgMGDKBXr16cc845J7293/zmNwwfPpzu3bvTv3//r3cyTzzxBBMnTuSZZ54hKyuLKVOmMGLECH75y19y3nnnkZWVRUFBAc8+++xJt0FS2JEj8NFHPtSr33bvjq6TlxcN6UGDju5tV79v2bJBhv1J4zDnXNBtOMqQIUNc7StMrV+/nj59+gTUovSg7zBNHTgAa9bAypXRQF+71pdhAJo3h/79fZgXFPj7/v2hdevg2iwJZ2bLnXNDYi1Tj14kVTgHO3Yc3UvfvDm6Tl6eD/NJk3ygDxrka8/Z+lXPZPrXD9gdd9zBggULarw2efJkbr755oBaJEmhvNyffFM71IuLo+ucfroP8h/+MBrqXbqoxCJHUdAH7Mknnwy6CRK0khJfeqke6B984Md2AzRrBv36wXe/Gy2/DBiQNCfjSPJT0Is0Bud8oBcXH32QdNMmvxygfXsf5LffHu2l9+6dsuO3JTko6EVORGkpfPFF/W7V50AB6NnTB/kPfhAN9W7dVHqRhFPQixw+7Icd1ie0v/oq9meZQYcO/oSh/Hwf5kOHRp/n5fl5UQYOBM1oKo1EQR+nE52mGODxxx9n4sSJ5ObmNkDLpE6ffALvvOPnLokV2vv3H/u9bdtGQ7pzZz8ssep5rFv79jpZSJKOgj5Ox5qmOB6PP/4448ePV9A3lr/9DUIhePttf6uaUyg3108PWxXKZ555/NDu0MEfCBVJcQr6OFWfpvg73/kOp5xyCi+//DKHDh3iyiuv5KGHHuLgwYNce+21FBUVUVFRwT/8wz+wc+dOduzYwbe+9S3y8/MJhUIxP//HP/4xS5cupbS0lGuuuYaHHnoIgKVLlzJ58mQOHjxI8+bNefvtt8nNzeW+++7j9ddfx8y49dZbmTRpUmN+Hcll3z54991osH/4oX+9XTs4/3z42c9gzBh/UFP1b8lAKRn0AUxHX2Oa4jfeeINZs2axZMkSnHNcfvnlzJs3j+LiYk499VRee+01wM+B07ZtWx577DFCodDXs0vG8vDDD9OhQwcqKioYM2YMa9asoXfv3lx33XW89NJLDB06lP3795OTk8O0adPYsmULK1euJDs7O/OmJS4rg4ULo8G+bJmfmConx884eMMNPtgLClRGESFFgz5ob7zxBm+88QYFBQUAlJSUsGnTJkaPHs0999zDfffdx2WXXcbo0aPj/syXX36ZadOmUV5ezueff866deswMzp37szQoUMBaBMZN/3WW29x2223kR052zHtJzArL4fly32ov/MOLFjgwz4ry8+M+MADPthHjPCn+4tIDSkZ9EFPR++c44EHHuBHP/rRUcuWL1/O3LlzeeCBB7jwwgv5x3/8xzo/b8uWLTz66KMsXbqU9u3bc9NNN1FWVnbM6YfTflpi5/yFH6p67OFw9IDpgAHw4x/7YB89WicNicQhvSZdbkDVpym+6KKLmD59OiUlJQBs376dXbt2sWPHDnJzcxk/fjz33HMPK1asOOq9sezfv5+WLVvStm1bdu7cyf/+7/8C0Lt3b3bs2MHSpUsBP3VxeXk5F154IVOnTqU8Mhd4WpRutm6FZ57xY8pPPdWfCTp5sp+c67rr4MUX/TS6q1fDY4/BpZcq5EXilJI9+iBUn6Z47NixfP/732fEiBEAtGrViueff57Nmzdz77330qRJE5o2bcqUKVMAmDhxImPHjqVz584xD8YOHDiQgoICvvnNb3LaaadRWFgIQLNmzXjppZeYNGkSpaWl5OTk8NZbbzFhwgQ2btzIgAEDaNq0Kbfeeit33nln430ZiVBc7MswVb32yDVw6dTJ99bHjIELLoAePQJtpkg60DTFGSTQ7/DAAZg3Lxrsa9b419u08SNjqsK9b1+NjBE5AZqmWIKxezfMmAF/+hMsWeJHxjRv7kfG/Mu/+B774MGaQlekgek3rJENHz6cQ1UXhIh47rnn6N+/f0AtSjDnYP58+P3vYdYsf/GLwYPhvvt8j33kSGjRIuhWimQUBX0jW7x4cdBNaBh79vje+7RpfqqBNm1gwgSYONGPlBGRwKRU0Kf9sMIG1CDHYpzzY9p//3tfnjl0CIYPh+nT4dpr/XVGRZJUZSV8/LG/AuOnn/ppjTp0OPqWDpfLTZmgb9GiBbt37yYvL09hX0/OOXbv3k2LRJVMvvwy2ntft8733m+5xffeBw5MzDZEEujwYf9fdeXK6G31aj9GoC7NmsXeAeTlHf/1Vq2SZweRMkHftWtXioqKKK5+KTWJW4sWLejateuJf4BzftqBadPg5Zf9manDhvmx79ddp967JI2qC3ZVD/W1a6OXA2jZ0vdHbrzRz5JRUABnnOFDf8+e6G337prPq25bt8KKFf7xsWarBj/GoD47hqpb27aJ/05SJuibNm1Kz549g25G5vnyS3juOR/wH34IrVvDzTf73vugQUG3TjLcF1/UDPSVK/2ldqsqlfn5PsjvuqtmqMeaAqlNG3/J3fooK/O/IsfbMVQt27bN/xWxZ4/fGcWSn1/zssCJkjJBL43IOVi0yNfeq3rvQ4fC00/73nurVkG3UDKMc/DZZ0eHelFRdJ3u3X2Qf//70VBv6Gult2jhL1PQuXP93nf4sN9B1N45VFQ0TDvjCnozuxh4AsgCnnbOPVJreXtgOnA6UAb8vXNubWTZ3cAEwAEfADc758oS9hNI4uzdG+29r13re+833eR775EJ3EQaWkWFv6xu9UBftcoHIUCTJn7G6fPOiwb6oEG+7JEqmjXzJ4F36tQ426sz6M0sC3gS+A5QBCw1s1edc+uqrfYLYJVz7koz6x1Zf4yZdQF+AvR1zpWa2cvAOODZBP8ccqKcg/ff9+H+0kv+WqhDhsBTT8G4ceq9S4MqK4MPPqgZ6mvW+P+G4M+vGzAArrkmGur9+/tryEj84unRDwM2O+c+ATCzF4ErgOpB3xf4VwDn3AYz62FmVfuqbCDHzI4AucCORDVeTsLevfD88z7gP/jAB/qNN/re+9lnB906SVO7dvkRufPn+9uKFX4WavAHIQsK4LbboqHeu7dOnE6EeL7CLsC2as+LgOG11lkNXAXMN7NhQHegq3NuuZk9CnwGlAJvOOfeiLURM5sITAT4u7/7u3r9EBIn52DxYh/uL77ou02DB/vn48b5Uo1IgjgHmzbVDPaNG/2yFi38oK177/X/BQsK/HXUk2U4YrqJJ+hjffW1z755BHjCzFbh6/ArgfJI7f4KoCewF/iTmY13zj1/1Ac6Nw2YBn5Ss3h/AInDvn3R3vuaNb73fsMNvvc+eHDCN1daCkuX+tGYCxfCli2+t9aunb92drt2dT9u08bXYlNRZSUcPOiH6x044EdYVH/coYPvqXbrlro/YyxHjvjSS1Woz58fHUGSlweFhf5k6VGj/B+NukZM44kn6IuAbtWed6VW+cU5tx+4GcD82UxbIreLgC3OueLIsleAkcBRQS8NYMkSP3LmxRf9gN+zz/bPr78+ob337dujob5wYc0/x886y4daSQns2OFPWtm719+Od7KuWXTnUJ8dRNXj3Nz4e4cVFTWDuXY41/W89rKDB+Pbbk5O9PupfjvrrNSoQe/f7w/vVIX64sXRceWnnw6XXOJDvbAQevVKr51aqokn6JcCZ5pZT2A7/mDq96uvYGbtgK+cc4fxI2zmOef2m9lnwDlmlosv3YwBas4/LIm3dy/ceSe88II/O+QHP4Af/Sghvffycj8WuHqwf/aZX1b15/g99/i5y0aM8OOCY6ms9KG4d68fZlYV/sd7vGlT9HFdYdq06dE7gOzs2GF9vJNeamvZ0u8jW7f2fxi1bu2H1p11VvR59WW1n7dq5Xu5GzZEb0uW+FGs1Xd83bsfvQPo3duP0giqvLF9e80yzOrV/t+xSRNfern11miw13e4oTSsuOajN7NLgMfxwyunO+ceNrPbAJxzU81sBDADqMAfpL3FOfdl5L0PAdcB5fiSzgTn3KGjtxIVaz56idO77/qDqtu3w4MPwk9/elJXYtqzx/faFi70v+RLlkSDsUsX/0s9cqS/DRzoh401hiNHfEUq3p3E3r1+JxUriI8VyrWft2zZcL3S0lK/I/voo5o7gQ0bau6I2raNvQM4/XS/c0uUyko/N938+dFw37LFL8vN9TvxUaP8bfhwHd5JBsebjz5lLjwidTh8GH71K/i3f/O/9c8/738D68E5HzTVe+vr1/tlWVl+rHJVqI8cCTpm3vAqK/0+u3b4b9jgS2FVsrP9P3vtHUCvXv4vmrocOgTLlkV76wsW+B0k+L8iqkJ91Ci/Q0/kTkUSQ0Gf7jZs8OWZFSv80a7//M+4xr9/9ZU/aLpggQ/1RYuiJ6W0b18z1IcO1XQ2yWb//th/AWza5P/iqdKp09E7gNNO8+tVBfvSpT7swS+vCvXCQr8D0WiY5KegT1fOwZQpviiem+unKPje9465+rZtNXvrq1ZFD5r27h0N9cJCX3PWwbPUVF7uyyy1dwLr10d35FWys/35cVXBPnIkdOwYTLvl5Cjo09HOnfD3fw9z58LFF/s54KsdAaus9B38qt76woXReUFycnxVpyrYzznHD3+T9PfFFz70N2/249aHDk2NET5SN10zNt38z//4+d8PHIDf/Q7uuAPMKC+H996D2bPhlVfg88/96t26RQ+aFhb6U8pVY81M+fnR3rtkDgV9Kjl4EH72Mz8WfuBAeOEFjpz1TUJv+suz/vnPfuheTg6MHQtXXuknfurWrc5PFpE0pqBPFcuW+QOumzZx6KcP8Oaoh5j9aFP+8hc/OqJVK7jsMrj6ah/yOnAqIlUU9MmuogIeeYTSXz3C/7Ubx6wL3uWvT3+D/Y/5MdWXX+5n9rvwQn/CkohIbQr6JFaydiuvXT2d2Rv7MTe7mIO7W9BhpQ/2a66BMWMa7wQlEUldCvoks28f/M+rjlmPb+P1FZ0o49ec0qaUG65vztXX+Jq7DqSKSH0o6JPA7t3w6qv+gOqbbzqOHDG60IRbT32Na/5zFIVXfyPmNS5FROKhoA/Izp1+lMzs2fDOO74U371TKT9p/t9cXfkCw399KU3uuzf2VYxFROpBQd+Itm+HOXN8z/299/xJTWecAffeXc41f/sdZz//U6xXLz/rZAPMEy8imUlB38A+/dT32mfP9menAvTt6yeWvPpq6G9rsfE/8BcEuf12+Pd/16mKIpJQCvoGsHmzD/ZZs/zwd/AzP/7mNz7c+/TBd+d/9zu47z4/TvKvf4VLLw2y2SKSphT0CVJUBC+9BDNnwvLl/rWhQ/2swVdd5Us0X9uxA266Cd5805/l9MwzcMopQTRbRDKAgv4kfPGF77XPnOlr7s750vqjj/px7t27x3jTK6/4S/GUlsLUqf66rZoDVkQakIK+ng4c8KNlZs70HfLycj/F7z/9E4wb56f3PeYb77rLzzI5eLA/4NqrV+M1XEQyloI+DmVlfjbgmTN9Kb2szF9d6ac/9dfZHjiwjk75okUwfjxs3Qq//KW/EpTOehKRRqKgP4bycnj7bR/uc+b4q/l07OhnB77+en/NzDovzFFeDv/8z/7WtSuEwzB6dGM0X0Tkawr6aior/RDImTPhT3/yU/62aeMPpl5/PVxwgb8iT1w2b/a9+MWL/cW6f/tbP7pGRKSRZXzQO+cvqTdzph8189lnfhbI737Xh/vYsScwK+Qf/gCTJvnyzEsvwbXXNkTTRUTikrFBv3GjD/eZM/21NbOz/VS/Dz8MV1wBrVuf4AevW+cv8Xf++fDcc75kIyISoIwK+m3bomPdV6zwB1DPPRfuvtufyJSfn4CNvPWWv3/2WYW8iCSFtA/64uKaY93BX/X+P/4DrrsOunRJ8AbDYX/V5ZiD6EVEGl9aBv3+/TXHuldU+GkHfv1rP9b9zDMbaMOVlfDuu772IyKSJNIm6I8c8XO6z5wJr73mx7p37w733OMPqg4Y0AgnoH7wAezZ4+vzIiJJIm2CvrISJkzwl9abMCE61r1RZxcIh/29gl5EkkjaBH3z5n4M/Jln1mOse6KFQnDaaf60WRGRJFHXuZ0ppU+fAEO+shLmzYNvfSugBoiIxJZWQR+oNWvgyy9VthGRpKOgT5RQyN8r6EUkySjoEyUc9lcX0UlSIpJkFPSJUFHhx8+rNy8iSUhBnwirV8O+fToQKyJJSUGfCFXj5887L9BmiIjEoqBPhFDID+BP+MQ5IiInT0F/sioqNH5eRJKagv5krVrlZ1HTgVgRSVIK+pOl8fMikuTiCnozu9jMPjKzzWZ2f4zl7c1sjpmtMbMlZtav2rJ2ZjbLzDaY2XozG5HIHyBw4TD06gWdOwfdEhGRmOoMejPLAp4ExgJ9gevNrG+t1X4BrHLODQBuBJ6otuwJ4P+cc72BgcD6RDQ8KZSX+/q8evMiksTi6dEPAzY75z5xzh0GXgRqX1mjL/A2gHNuA9DDzDqZWRvgXOCZyLLDzrm9iWp84FauhAMHdCBWRJJaPEHfBdhW7XlR5LXqVgNXAZjZMKA70BU4DSgG/mBmK83saTNrGWsjZjbRzJaZ2bLi4uJ6/hgB0fh5EUkB8QR9rEt3uFrPHwHam9kqYBKwEijHz3d/NjDFOVcAHASOqvEDOOemOeeGOOeGdOzYMc7mBywUgt694RvfCLolIiLHFM/s7UVAt2rPuwI7qq/gnNsP3AxgZgZsidxygSLn3OLIqrM4RtCnnPJyf7XxG24IuiUiIscVT49+KXCmmfU0s2bAOODV6itERtY0izydAMxzzu13zv0N2GZmvSLLxgDrEtT2YC1fDiUlOhArIkmvzh69c67czO4EXgeygOnOuQ/N7LbI8qlAH2CGmVXgg/yWah8xCXghsiP4hEjPP+Xp+rAikiLiuvCec24uMLfWa1OrPV4EnHmM964Chpx4E5NUOAx9+8IppwTdEhGR49KZsSfiyBFfn1dvXkRSgIL+RCxfDgcPavy8iKQEBf2J0Ph5EUkhCvoTEQpBv36QKuP9RSSjKejr68gRmD9f9XkRSRkK+vpauhS++kpBLyIpQ0FfX6rPi0iKUdDXVzgM/ftDfn7QLRERiYuCvj4OH4YFC1S2EZGUoqCvj6r6vMbPi0gKUdDXRygEZnDuuUG3REQkbgr6+giHYcAAyMsLuiUiInFT0Mfr0CFYuFD1eRFJOQr6eC1ZAqWlCnoRSTkK+niFw6rPi0hKUtDHKxyGgQOhQ4egWyIiUi8K+nhU1ec1rFJEUpCCPh6LF0NZmerzIpKSFPTxqBo/P3p00C0REak3BX08wmEoKID27YNuiYhIvSno61JWBosWqWwjIilLQV+X99/3B2MV9CKSohT0dQmHoUkT1edFJGUp6OsSCvn6fLt2QbdEROSEKOiPp7TUl240fl5EUpiC/njef99fbET1eRFJYQr64wmFfH1+1KigWyIicsIU9McTDsPgwdC2bdAtERE5YQr6Y/nqKz/1gco2IpLiFPTHsmiRr8/rQKyIpDgF/bGEw5CVBYWFQbdEROSkKOiPJRTy9fk2bYJuiYjISVHQx3LwoL90oMo2IpIGFPSxLFoER47oQKyIpAUFfSyhkK/Pa/y8iKQBBX0s4TAMHQqtWgXdEhGRk6agr62kxNfnVbYRkTShoK9t4UIoL9eBWBFJGwr62sJhyM6GkSODbomISELEFfRmdrGZfWRmm83s/hjL25vZHDNbY2ZLzKxfreVZZrbSzP6aqIY3mFBI9XkRSSt1Br2ZZQFPAmOBvsD1Zta31mq/AFY55wYANwJP1Fo+GVh/8s1tYCUlsHSpyjYiklbi6dEPAzY75z5xzh0GXgSuqLVOX+BtAOfcBqCHmXUCMLOuwKXA0wlrdUNZsAAqKnQgVkTSSjxB3wXYVu15UeS16lYDVwGY2TCgO9A1suxx4OdA5fE2YmYTzWyZmS0rLi6Oo1kNIBSCpk1VnxeRtBJP0FuM11yt548A7c1sFTAJWAmUm9llwC7n3PK6NuKcm+acG+KcG9KxY8c4mtUAwmEYNgxatgxm+yIiDSCeoC8CulV73hXYUX0F59x+59zNzrlB+Bp9R2ALUAhcbmZb8SWfC8zs+QS0O/EOHIBly1S2EZG0E0/QLwXONLOeZtYMGAe8Wn0FM2sXWQYwAZgXCf8HnHNdnXM9Iu97xzk3PoHtT5z58319XgdiRSTNZNe1gnOu3MzuBF4HsoDpzrkPzey2yPKpQB9ghplVAOuAWxqwzQ0jHPb1+REjgm6JiEhCmXO1y+3BGzJkiFu2bFnjbnTYMGjRAubNa9ztiogkgJktd84NibVMZ8YC7N8Py5erPi8iaUlBD/Dee1BZqaAXkbSkoAdfn2/WTPV5EUlLCnrwQX/OOZCTE3RLREQSTkG/bx+sWKGyjYikLQV9VX1e4+dFJE0p6MNhaN7cl25ERNKQgj4U8gdhW7QIuiUiIg0is4N+715YuVL1eRFJa5kd9PPmgXMKehFJa5kd9OGwL9kMHx50S0REGoyCXvV5EUlzmRv0e/bAqlUaVikiaS9zg/6991SfF5GMkLlBHwr5ks2wYUG3RESkQWVu0IfDUFjoT5YSEUljmRn0e/bAmjUq24hIRsjMoH/3XV+f14FYEckAmRn04bCfknjo0KBbIiLS4DI36AsL/cVGRETSXOYF/Rdf+Pq8yjYikiEyL+jnzfP3OhArIhki84I+FILcXBgyJOiWiIg0iswL+nAYRo1SfV5EMkZmBX1xMaxdq7KNiGSUzAr6d9/19zoQKyIZJLOCPhyGli1h8OCgWyIi0mgyK+hDIV+fb9o06JaIiDSazAn6Xbtg3TqVbUQk42RO0FfV53UgVkQyTOYEfSgErVqpPi8iGSdzgj4chtGjITs76JaIiDSqzAj6nTth/XqVbUQkI2VG0IfD/l4HYkUkA2VO0LduDQUFQbdERKTRZUbQh0Kqz4tIxkr/oP/8c/joI5VtRCRjpX/Qa/y8iGS49A/6UAjatFF9XkQyVlxBb2YXm9lHZrbZzO6Psby9mc0xszVmtsTM+kVe72ZmITNbb2YfmtnkRP8AdQqH4dxzISur0TctIpIM6gx6M8sCngTGAn2B682sb63VfgGscs4NAG4Enoi8Xg78zDnXBzgHuCPGexvOjh2wcaPKNiKS0eLp0Q8DNjvnPnHOHQZeBK6otU5f4G0A59wGoIeZdXLOfe6cWxF5/QCwHuiSsNbXRePnRUTiCvouwLZqz4s4OqxXA1cBmNkwoDvQtfoKZtYDKAAWx9qImU00s2Vmtqy4uDiuxtcpHIZ27WDgwMR8nohICoon6C3Ga67W80eA9ma2CpgErMSXbfwHmLUCZgN3Oef2x9qIc26ac26Ic25Ix44d42l73UIh1edFJOPFcwZREdCt2vOuwI7qK0TC+2YAMzNgS+SGmTXFh/wLzrlXEtDm+BQVwebNcPvtjbZJEZFkFE+Pfilwppn1NLNmwDjg1eormFm7yDKACcA859z+SOg/A6x3zj2WyIbXSePnRUSAOHr0zrlyM7sTeB3IAqY75z40s9siy6cCfYAZZlYBrANuiby9ELgB+CBS1gH4hXNubmJ/jBhCIWjfXvV5Ecl4cU3+EgnmubVem1rt8SLgzBjvm0/sGn/Dqxo/3yT9zwkTETme9EzBbdvg4481rFJEhHQN+qrx86rPi4ikcdB36AD9+wfdEhGRwKVn0IdCcN55qs+LiJCOQf/pp7Bli8o2IiIR6Rf0qs+LiNSQnkGflwf9+gXdEhGRpJCeQa/6vIjI19IrDbdu9TeNnxcR+Vp6Bb3q8yIiR0m/oM/Ph76NdxErEZFklz5B75wfP3/++arPi4hUE9ekZinh0CEYMwa+/e2gWyIiklTSJ+hbtIDp04NuhYhI0lGNQ0QkzSnoRUTSnIJeRCTNKehFRNKcgl5EJM0p6EVE0pyCXkQkzSnoRUTSnDnngm7DUcysGPg06HacpHzgi6AbkST0XdSk76MmfR9RJ/NddHfOdYy1ICmDPh2Y2TLn3JCg25EM9F3UpO+jJn0fUQ31Xah0IyKS5hT0IiJpTkHfcKYF3YAkou+iJn0fNen7iGqQ70I1ehGRNKcevYhImlPQi4ikOQV9AplZNzMLmdl6M/vQzCYH3aagmVmWma00s78G3ZagmVk7M5tlZhsi/0dGBN2mIJnZ3ZHfk7VmNtPMWgTdpsZkZtPNbJeZra32Wgcze9PMNkXu2ydiWwr6xCoHfuac6wOcA9xhZpl+pfLJwPqgG5EkngD+zznXGxhIBn8vZtYF+AkwxDnXD8gCxgXbqkb3LHBxrdfuB952zp0JvB15ftIU9AnknPvcObci8vgA/he5S7CtCo6ZdQUuBZ4Oui1BM7M2wLnAMwDOucPOub2BNip42UCOmWUDucCOgNvTqJxz84A9tV6+AvjvyOP/Br6XiG0p6BuImfUACoDFATclSI8DPwcqA25HMjgNKAb+ECllPW1mLYNuVFCcc9uBR4HPgM+Bfc65N4JtVVLo5Jz7HHzHETglER+qoG8AZtYKmA3c5ZzbH3R7gmBmlwG7nHPLg25LksgGzgamOOcKgIMk6M/yVBSpPV8B9AROBVqa2fhgW5W+FPQJZmZN8SH/gnPulaDbE6BC4HIz2wq8CFxgZs8H26RAFQFFzrmqv/Bm4YM/U30b2OKcK3bOHQFeAUYG3KZksNPMOgNE7ncl4kMV9AlkZoavwa53zj0WdHuC5Jx7wDnX1TnXA3+Q7R3nXMb22JxzfwO2mVmvyEtjgHUBNilonwHnmFlu5PdmDBl8cLqaV4EfRh7/EPhLIj40OxEfIl8rBG4APjCzVZHXfuGcmxtckySJTAJeMLNmwCfAzQG3JzDOucVmNgtYgR+ttpIMmwrBzGYC5wP5ZlYE/Ap4BHjZzG7B7wz/X0K2pSkQRETSm0o3IiJpTkEvIpLmFPQiImlOQS8ikuYU9CIiaU5BLyKS5hT0IiJp7v8DTApsl0HK7PIAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "\n",
    "acc = h4.history[\"accuracy\"]\n",
    "val_acc = h4.history[\"val_accuracy\"]\n",
    "\n",
    "e = range(1, len(acc) +1)\n",
    "\n",
    "plt.plot(e, acc, \"-\", color=\"red\", label=\"train_acc\")\n",
    "plt.plot(e, val_acc, \"-\", color=\"blue\", label=\"test_acc\")\n",
    "plt.legend()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 기존 손글씨 모델의 제약사항\n",
    "1. 모든 손글씨 이미지의 배경이 깔끔하다(0으로 뎅터화)\n",
    "2. 손글씨의 각도가 일정하다(회전x)\n",
    "3. 손글씨의 크기가 일정하다 (비슷한 크키로 중앙에 배치)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
